import { createHash, randomUUID } from 'node:crypto';
import {
  chmod,
  copyFile,
  lstat,
  mkdir,
  readFile,
  rename,
  unlink,
  writeFile,
} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { DEFAULT_PUBLIC_PORT } from '../constants.js';
import type {
  ServiceInstallCommandResult,
  ServiceInstallCommandRunner,
  ServiceInstallElevatedCommand,
  ServiceInstallationRecord,
  ServiceInstallOptions,
} from '../interfaces/service-install-options.js';
import { LocalTlsService } from '../service.js';
import { sanitizeNamespace } from '../state-paths.js';

export const LEGACY_STARTUP_SERVICE_OWNER_MARKER = 'generated by @vampaz/vite-plugin-local-tls';
export const STARTUP_SERVICE_OWNER_MARKER =
  'managed startup-service-v2 by @vampaz/vite-plugin-local-tls';
export const OWNER_MARKER = STARTUP_SERVICE_OWNER_MARKER;
export const CANONICAL_SERVICE_NAMESPACE = 'default';
export const MACOS_ELEVATED_SEQUENCE_SOURCE = [
  'import { spawnSync } from "node:child_process";',
  'const commands = JSON.parse(process.argv[1]);',
  'const rollback = [];',
  'for (const request of commands) {',
  '  const child = spawnSync(request.command, request.arguments_, { stdio: "inherit", timeout: request.timeoutMs ?? 15_000 });',
  '  if (child.error) console.error(child.error.message);',
  '  if (child.error || child.status !== 0) {',
  '    if (request.allowFailure) continue;',
  '    rollback: for (const group of [...rollback].reverse()) {',
  '      for (const recovery of group) {',
  '        const restored = spawnSync(recovery.command, recovery.arguments_, { stdio: "inherit", timeout: recovery.timeoutMs ?? 15_000 });',
  '        if ((restored.error || restored.status !== 0) && !recovery.allowFailure) break rollback;',
  '      }',
  '    }',
  '    process.exit(child.status ?? 1);',
  '  }',
  '  if (request.clearRollbackAfterSuccess) rollback.length = 0;',
  '  if (request.discardRollbackAfterSuccess) rollback.pop();',
  '  if (request.rollbackAfterSuccess?.length) rollback.push(request.rollbackAfterSuccess);',
  '}',
].join('\n');

export interface ObsoleteServiceInstallation {
  installation: ServiceInstallOptions;
  record: ServiceInstallationRecord;
  wasRunning?: boolean;
}

export interface MacosControlClient {
  nodePath: string;
  cliPath: string;
}

export function xmlEscape(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

export function systemdQuote(value: string): string {
  return `"${value.replaceAll('%', '%%').replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;
}

export function linuxUserRuntimeUnit(options: ServiceInstallOptions): string | null {
  const match = /^\/run\/user\/(\d+)(?:\/|$)/.exec(options.paths.runtimeDirectory);
  if (!match) {
    return null;
  }
  const runtimeUid = Number(match[1]);
  const uid = options.uid ?? process.getuid?.() ?? os.userInfo().uid;
  if (!Number.isSafeInteger(runtimeUid) || runtimeUid !== uid) {
    throw new Error('The Linux runtime directory does not belong to the installing user.');
  }
  return `user-runtime-dir@${uid}.service`;
}

export function xmlDecode(value: string): string | null {
  if (/&(?!amp;|apos;|gt;|lt;|quot;|#\d+;|#x[\dA-Fa-f]+;)/.test(value)) {
    return null;
  }
  return value.replace(/&(amp|apos|gt|lt|quot|#\d+|#x[\dA-Fa-f]+);/g, (_match, entity: string) => {
    if (entity === 'amp') return '&';
    if (entity === 'apos') return "'";
    if (entity === 'gt') return '>';
    if (entity === 'lt') return '<';
    if (entity === 'quot') return '"';
    const codePoint = Number.parseInt(
      entity.slice(entity[1] === 'x' ? 2 : 1),
      entity[1] === 'x' ? 16 : 10,
    );
    return Number.isSafeInteger(codePoint) && codePoint <= 0x10ffff
      ? String.fromCodePoint(codePoint)
      : '\uFFFD';
  });
}

export function xmlWithoutComments(contents: string): string {
  return contents.replaceAll(/<!--[\s\S]*?-->/g, '');
}

export function singleXmlContainer(contents: string, element: string): string | null {
  const expression = new RegExp(`<${element}(?:\\s[^>]*)?>([\\s\\S]*?)</${element}>`, 'g');
  const matches = [...contents.matchAll(expression)];
  return matches.length === 1 ? matches[0]![1]! : null;
}

export function singleWindowsExecAction(
  contents: string,
): { command: string; arguments_: string } | null {
  const exec = /^\s*<Exec(?:\s+id="[^"<>&]*")?>([\s\S]*?)<\/Exec>\s*$/.exec(contents);
  if (!exec) {
    return null;
  }
  const action = /^\s*<Command>([\s\S]*?)<\/Command>\s*<Arguments>([\s\S]*?)<\/Arguments>\s*$/.exec(
    exec[1]!,
  );
  if (!action) {
    return null;
  }
  const command = xmlDecode(action[1]!);
  const arguments_ = xmlDecode(action[2]!);
  return command === null || arguments_ === null ? null : { command, arguments_ };
}

export function ownerMarker(record: ServiceInstallationRecord): string {
  return record.version === 1 ? LEGACY_STARTUP_SERVICE_OWNER_MARKER : OWNER_MARKER;
}

export function normalizeXmlDefinition(contents: string): string {
  return xmlWithoutComments(contents).replaceAll(/>\s+</g, '><').trim();
}

export function normalizeSystemdDefinition(contents: string): string[] {
  return contents
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#') && !line.startsWith(';'));
}

export function serviceDefinitionMatchesInstallation(
  contents: string,
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
): boolean {
  if (record.platform === 'darwin') {
    const expected = launchdDefinition(
      {
        ...options,
        nodePath: record.nodePath,
        cliPath: record.cliPath,
        controlSocket: record.controlSocket ?? undefined,
      },
      record.identifier,
      record.version,
    );
    return (
      contents.includes(`<!-- ${ownerMarker(record)} -->`) &&
      normalizeXmlDefinition(contents) === normalizeXmlDefinition(expected)
    );
  }
  if (record.platform === 'linux') {
    const expected = systemdDefinition(
      {
        ...options,
        nodePath: record.nodePath,
        cliPath: record.cliPath,
        controlSocket: record.controlSocket ?? undefined,
      },
      record.version,
    );
    return (
      contents.split(/\r?\n/).some((line) => line.trim() === `# ${ownerMarker(record)}`) &&
      JSON.stringify(normalizeSystemdDefinition(contents)) ===
        JSON.stringify(normalizeSystemdDefinition(expected))
    );
  }
  return record.platform === 'win32';
}

export function windowsQuote(value: string): string {
  return `"${value.replaceAll(/(\\*)"/g, '$1$1\\"').replaceAll(/(\\+)$/g, '$1$1')}"`;
}

export function validateDefinitionValue(value: string, label: string): string {
  const hasControlCharacter = [...value].some((character) => {
    const codePoint = character.codePointAt(0) ?? 0;
    return codePoint < 32 || codePoint === 127;
  });
  if (!value || hasControlCharacter) {
    throw new Error(`${label} contains unsupported control characters.`);
  }
  return value;
}

export function safeServiceKey(options: ServiceInstallOptions): string {
  const platform = options.platform ?? process.platform;
  const key = sanitizeNamespace(options.namespace);
  if (!/^[a-z0-9-]{1,40}$/.test(key)) {
    throw new Error(`Unsafe service namespace: ${key}`);
  }
  validateDefinitionValue(options.namespace, 'Service namespace');
  if (options.namespace.length > 256) {
    throw new Error('Service namespace exceeds 256 characters.');
  }
  validateDefinitionValue(options.nodePath, 'Node path');
  validateDefinitionValue(options.cliPath, 'CLI path');
  validateDefinitionValue(options.homeDirectory ?? os.homedir(), 'Home directory');
  validateDefinitionValue(options.username ?? os.userInfo().username, 'Username');
  validateDefinitionValue(options.paths.stateDirectory, 'State directory');
  validateDefinitionValue(options.paths.runtimeDirectory, 'Runtime directory');
  validateDefinitionValue(options.paths.socketPath, 'Control socket');
  if (options.controlSocket) {
    validateDefinitionValue(options.controlSocket, 'Control socket');
    if (options.controlSocket.length > 4096) {
      throw new Error('Control socket exceeds 4096 characters.');
    }
  }
  if (options.runtimeInstallDirectory) {
    validateDefinitionValue(options.runtimeInstallDirectory, 'Service runtime directory');
  }
  if (
    platform === 'linux' &&
    !/^[a-zA-Z_][a-zA-Z0-9_-]*\$?$/.test(options.username ?? os.userInfo().username)
  ) {
    throw new Error('Username cannot be represented safely in a systemd service.');
  }
  if (platform === 'darwin') {
    for (const [label, value] of [
      ['User ID', options.uid ?? os.userInfo().uid],
      ['Group ID', options.gid ?? os.userInfo().gid],
    ] as const) {
      if (!Number.isSafeInteger(value) || value < 0) {
        throw new Error(`${label} must be a non-negative integer.`);
      }
    }
  }
  return key;
}

export function recordPath(options: ServiceInstallOptions, version: 1 | 2): string {
  return path.join(
    options.paths.stateDirectory,
    version === 2 ? 'service-install-v2.json' : 'service-install.json',
  );
}

export function previousRecordPath(options: ServiceInstallOptions): string {
  return path.join(options.paths.stateDirectory, 'service-install-previous.json');
}

export async function removeInstallationRecords(options: ServiceInstallOptions): Promise<void> {
  await Promise.all(
    [recordPath(options, 1), recordPath(options, 2), previousRecordPath(options)].map((filePath) =>
      unlink(filePath).catch((error: NodeJS.ErrnoException) => {
        if (error.code !== 'ENOENT') {
          throw error;
        }
      }),
    ),
  );
}

export function serviceIdentifier(platform: NodeJS.Platform, key: string): string {
  return platform === 'darwin'
    ? `com.vampaz.vite-local-tls.${key}`
    : platform === 'win32'
      ? `Vite Local TLS\\${key}`
      : `vite-local-tls-${key}`;
}

export function expectedDefinitionPath(
  options: ServiceInstallOptions,
  platform: NodeJS.Platform,
  identifier: string,
): string | null {
  if (platform === 'darwin') {
    return path.join(
      options.definitionDirectory ?? '/Library/LaunchDaemons',
      `${identifier}.plist`,
    );
  }
  if (platform === 'linux') {
    return path.join(options.definitionDirectory ?? '/etc/systemd/system', `${identifier}.service`);
  }
  return null;
}

export function expectedRuntimeDirectory(
  options: ServiceInstallOptions,
  platform: NodeJS.Platform,
  key: string,
): string {
  if (options.runtimeInstallDirectory) {
    return options.runtimeInstallDirectory;
  }
  if (platform === 'darwin') {
    return path.join('/Library/Application Support/vite-plugin-local-tls', key);
  }
  if (platform === 'win32') {
    return path.join(
      path.dirname(path.dirname(options.paths.stateDirectory)),
      'vlt',
      windowsRuntimeKey(key),
    );
  }
  return path.join(options.paths.stateDirectory, 'service-runtime');
}

export function windowsRuntimeKey(key: string): string {
  return createHash('sha256').update(key).digest('hex').slice(0, 12);
}

export function assertExpectedRecord(
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
): void {
  const platform = options.platform ?? process.platform;
  const key = safeServiceKey(options);
  const identifier = serviceIdentifier(platform, key);
  const definitionPath = expectedDefinitionPath(options, platform, identifier);
  if (record.identifier !== identifier || record.definitionPath !== definitionPath) {
    throw new Error('Service installation record contains unexpected system targets.');
  }
  const runtimeDirectory = expectedRuntimeDirectory(options, platform, key);
  const cliPath = path.join(
    runtimeDirectory,
    platform === 'darwin' ? 'cli.js' : platform === 'win32' ? 'c.js' : `cli-${key}.js`,
  );
  const nodePath = path.join(runtimeDirectory, platform === 'win32' ? 'n.exe' : 'node');
  if (
    record.runtimeDirectory !== runtimeDirectory ||
    record.cliPath !== cliPath ||
    record.nodePath !== nodePath
  ) {
    throw new Error('Service installation record contains an unexpected runtime target.');
  }
}

export async function readRegularInstallationRecord(filePath: string): Promise<string> {
  const details = await lstat(filePath);
  if (!details.isFile() || details.isSymbolicLink()) {
    throw new Error(`Refusing unsafe service installation record: ${filePath}`);
  }
  return readFile(filePath, 'utf8');
}

export async function readRecord(
  options: ServiceInstallOptions,
): Promise<ServiceInstallationRecord | null> {
  let contents: string;
  let recordVersion: 1 | 2 | null = 2;
  let recoveredPreviousRecord = false;
  try {
    contents = await readRegularInstallationRecord(recordPath(options, 2));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
    recordVersion = 1;
    try {
      contents = await readRegularInstallationRecord(recordPath(options, 1));
    } catch (legacyError) {
      if ((legacyError as NodeJS.ErrnoException).code !== 'ENOENT') {
        throw legacyError;
      }
      try {
        contents = await readRegularInstallationRecord(previousRecordPath(options));
        recordVersion = null;
        recoveredPreviousRecord = true;
      } catch (previousError) {
        if ((previousError as NodeJS.ErrnoException).code === 'ENOENT') {
          return null;
        }
        throw previousError;
      }
    }
  }
  const record = JSON.parse(contents) as ServiceInstallationRecord;
  if (
    (recordVersion !== null && record.version !== recordVersion) ||
    (record.version !== 1 && record.version !== 2) ||
    record.namespace !== options.namespace ||
    record.platform !== (options.platform ?? process.platform) ||
    (record.version === 2 &&
      (typeof record.packageVersion !== 'string' ||
        !Number.isInteger(record.protocolVersion) ||
        record.protocolVersion < 1 ||
        (record.installationState !== 'installing' && record.installationState !== 'installed') ||
        (recoveredPreviousRecord && record.installationState !== 'installed')))
  ) {
    throw new Error('Service installation record does not match this namespace and platform.');
  }
  assertExpectedRecord(options, record);
  return record;
}

export async function readPreviousRecord(
  options: ServiceInstallOptions,
): Promise<ServiceInstallationRecord | null> {
  let contents: string;
  try {
    contents = await readRegularInstallationRecord(previousRecordPath(options));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return null;
    }
    throw error;
  }
  const record = JSON.parse(contents) as ServiceInstallationRecord;
  if (
    (record.version !== 1 && record.version !== 2) ||
    record.namespace !== options.namespace ||
    record.platform !== (options.platform ?? process.platform) ||
    (record.version === 2 &&
      (typeof record.packageVersion !== 'string' ||
        !Number.isInteger(record.protocolVersion) ||
        record.protocolVersion < 1 ||
        record.installationState !== 'installed'))
  ) {
    throw new Error('Previous service installation record is invalid.');
  }
  assertExpectedRecord(options, record);
  return record;
}

export function installedService(options: ServiceInstallOptions): LocalTlsService {
  return new LocalTlsService({
    paths: options.paths,
    opensslPath: 'openssl',
    namespace: options.namespace,
    port: DEFAULT_PUBLIC_PORT,
  });
}

export function optionsForInstallationRecord(
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
): ServiceInstallOptions {
  if (
    options.controlSocket !== undefined &&
    options.controlSocket !== (record.controlSocket ?? undefined)
  ) {
    throw new Error(
      'The requested control channel does not match the service installation record.',
    );
  }
  const controlSocket = record.controlSocket ?? undefined;
  return {
    ...options,
    paths: controlSocket ? { ...options.paths, socketPath: controlSocket } : options.paths,
    controlSocket,
  };
}

export async function quiesceInstalledService(options: ServiceInstallOptions): Promise<boolean> {
  return installedService(options).stopIfIdle();
}

export async function waitForStartupServiceReady(options: ServiceInstallOptions): Promise<void> {
  if (options.waitForServiceReady) {
    await options.waitForServiceReady();
    return;
  }
  if (options.runner) {
    return;
  }
  const service = installedService(options);
  const deadline = Date.now() + 30_000;
  let lastError: unknown;
  while (Date.now() < deadline) {
    try {
      const status = await service.status();
      if (status.running && status.compatible) {
        return;
      }
    } catch (error) {
      lastError = error;
    }
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  throw new Error('Timed out waiting for the installed local TLS service to become ready.', {
    cause: lastError,
  });
}

export async function writeRecord(
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
): Promise<void> {
  const finalPath = recordPath(options, record.version);
  const temporaryPath = `${finalPath}.${process.pid}.${randomUUID()}.tmp`;
  try {
    await writeFile(temporaryPath, `${JSON.stringify(record, null, 2)}\n`, { mode: 0o600 });
    await rename(temporaryPath, finalPath);
  } finally {
    await unlink(temporaryPath).catch(() => undefined);
  }
}

export async function writePreviousRecord(
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
): Promise<void> {
  const finalPath = previousRecordPath(options);
  const temporaryPath = `${finalPath}.${process.pid}.${randomUUID()}.tmp`;
  try {
    await writeFile(temporaryPath, `${JSON.stringify(record, null, 2)}\n`, { mode: 0o600 });
    await rename(temporaryPath, finalPath);
  } finally {
    await unlink(temporaryPath).catch(() => undefined);
  }
}

export async function assertOwnedDefinition(
  definitionPath: string,
  expectation?:
    | { options: ServiceInstallOptions; record: ServiceInstallationRecord }
    | Array<{ options: ServiceInstallOptions; record: ServiceInstallationRecord }>,
  requireExisting = false,
): Promise<void> {
  try {
    const details = await lstat(definitionPath);
    if (!details.isFile() || details.isSymbolicLink()) {
      throw new Error(`Refusing unsafe service definition: ${definitionPath}`);
    }
    const contents = await readFile(definitionPath, 'utf8');
    const expectations = Array.isArray(expectation)
      ? expectation
      : expectation
        ? [expectation]
        : [];
    if (
      expectations.length === 0 ||
      !expectations.some(({ options, record }) =>
        serviceDefinitionMatchesInstallation(contents, options, record),
      )
    ) {
      throw new Error(`Refusing to overwrite unrelated service definition: ${definitionPath}`);
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT' && requireExisting) {
      throw new Error(`The recorded startup service definition is missing: ${definitionPath}`);
    }
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
  }
}

export function launchdDefinition(
  options: ServiceInstallOptions,
  identifier: string,
  recordVersion: 1 | 2 = 2,
): string {
  const user = os.userInfo();
  const username = options.username ?? user.username;
  const uid = options.uid ?? user.uid;
  const gid = options.gid ?? user.gid;
  const arguments_ = [
    options.nodePath,
    options.cliPath,
    'proxy',
    'start',
    '--service',
    '--namespace',
    options.namespace,
    '--run-as-uid',
    String(uid),
    '--run-as-gid',
    String(gid),
  ];
  if (options.controlSocket) {
    arguments_.push('--control-socket', options.controlSocket);
  }
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    '<dict>',
    `  <!-- ${recordVersion === 1 ? LEGACY_STARTUP_SERVICE_OWNER_MARKER : OWNER_MARKER} -->`,
    '  <key>Label</key>',
    `  <string>${xmlEscape(identifier)}</string>`,
    '  <key>ProgramArguments</key>',
    '  <array>',
    ...arguments_.map((argument) => `    <string>${xmlEscape(argument)}</string>`),
    '  </array>',
    '  <key>EnvironmentVariables</key>',
    '  <dict>',
    '    <key>HOME</key>',
    `    <string>${xmlEscape(options.homeDirectory ?? os.homedir())}</string>`,
    '    <key>USER</key>',
    `    <string>${xmlEscape(username)}</string>`,
    '    <key>LOGNAME</key>',
    `    <string>${xmlEscape(username)}</string>`,
    '    <key>VITE_LOCAL_TLS_USER_ID</key>',
    `    <string>${uid}</string>`,
    '    <key>VITE_LOCAL_TLS_RUNTIME_DIRECTORY</key>',
    `    <string>${xmlEscape(options.paths.runtimeDirectory)}</string>`,
    '  </dict>',
    '  <key>RunAtLoad</key>',
    '  <true/>',
    '  <key>KeepAlive</key>',
    ...(recordVersion === 1
      ? ['  <true/>']
      : ['  <dict>', '    <key>SuccessfulExit</key>', '    <false/>', '  </dict>']),
    '  <key>ProcessType</key>',
    '  <string>Background</string>',
    '  <key>StandardOutPath</key>',
    `  <string>${xmlEscape(path.join(options.paths.stateDirectory, 'service.log'))}</string>`,
    '  <key>StandardErrorPath</key>',
    `  <string>${xmlEscape(path.join(options.paths.stateDirectory, 'service-error.log'))}</string>`,
    '</dict>',
    '</plist>',
    '',
  ].join('\n');
}

export async function installUserRuntime(
  options: ServiceInstallOptions,
  key: string,
): Promise<{ nodePath: string; cliPath: string; runtimeDirectory: string }> {
  const runtimeDirectory =
    options.runtimeInstallDirectory ??
    expectedRuntimeDirectory(
      options,
      options.platform ?? process.platform,
      safeServiceKey(options),
    );
  const nodePath = path.join(
    runtimeDirectory,
    (options.platform ?? process.platform) === 'win32' ? 'n.exe' : 'node',
  );
  const cliPath = path.join(
    runtimeDirectory,
    (options.platform ?? process.platform) === 'win32' ? 'c.js' : `cli-${key}.js`,
  );
  await mkdir(runtimeDirectory, { recursive: true, mode: 0o700 });
  await Promise.all([
    replaceRuntimeFile(options.nodePath, nodePath, options.platform ?? process.platform),
    replaceRuntimeFile(options.cliPath, cliPath, options.platform ?? process.platform),
  ]);
  return { nodePath, cliPath, runtimeDirectory };
}

export async function replaceRuntimeFile(
  sourcePath: string,
  destinationPath: string,
  platform: NodeJS.Platform,
): Promise<void> {
  const temporaryPath = `${destinationPath}.${process.pid}.${randomUUID()}.tmp`;
  await copyFile(sourcePath, temporaryPath);
  try {
    if (platform !== 'win32') {
      await chmod(temporaryPath, 0o700);
      await rename(temporaryPath, destinationPath);
      return;
    }
    let lastError: unknown;
    for (let attempt = 0; attempt < 20; attempt += 1) {
      try {
        await copyFile(temporaryPath, destinationPath);
        return;
      } catch (error) {
        lastError = error;
        const code = (error as NodeJS.ErrnoException).code;
        if (!['EBUSY', 'EACCES', 'EPERM'].includes(code ?? '') || attempt === 19) {
          throw error;
        }
        await new Promise((resolve) => setTimeout(resolve, 50));
      }
    }
    throw lastError;
  } finally {
    await unlink(temporaryPath).catch(() => undefined);
  }
}

export async function stageRegularFileBackup(
  sourcePath: string,
  backupPath: string,
): Promise<void> {
  const details = await lstat(sourcePath);
  if (!details.isFile() || details.isSymbolicLink()) {
    throw new Error(`Refusing unsafe installed service runtime: ${sourcePath}`);
  }
  try {
    const backupDetails = await lstat(backupPath);
    if (!backupDetails.isFile() || backupDetails.isSymbolicLink()) {
      throw new Error(`Refusing unsafe installed service backup: ${backupPath}`);
    }
    return;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
  }
  const temporaryPath = `${backupPath}.${process.pid}.${randomUUID()}.tmp`;
  try {
    await copyFile(sourcePath, temporaryPath);
    await rename(temporaryPath, backupPath);
  } finally {
    await unlink(temporaryPath).catch(() => undefined);
  }
}

export function serviceBackupKey(
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
): string {
  const fingerprint = createHash('sha256')
    .update(JSON.stringify(record))
    .digest('hex')
    .slice(0, 12);
  return `${safeServiceKey(options)}-${fingerprint}`;
}

export function systemdDefinition(
  options: ServiceInstallOptions,
  recordVersion: 1 | 2 = 2,
): string {
  const username = options.username ?? os.userInfo().username;
  const runtimeUnit = recordVersion === 2 ? linuxUserRuntimeUnit(options) : null;
  const arguments_ = [
    options.nodePath,
    options.cliPath,
    'proxy',
    'start',
    '--service',
    '--namespace',
    options.namespace,
  ];
  if (options.controlSocket) {
    arguments_.push('--control-socket', options.controlSocket);
  }
  return [
    `# ${recordVersion === 1 ? LEGACY_STARTUP_SERVICE_OWNER_MARKER : OWNER_MARKER}`,
    '[Unit]',
    'Description=Vite local TLS proxy',
    `After=network.target${runtimeUnit ? ` ${runtimeUnit}` : ''}`,
    ...(runtimeUnit ? [`Requires=${runtimeUnit}`] : []),
    '',
    '[Service]',
    'Type=simple',
    `User=${username}`,
    `Environment=HOME=${systemdQuote(options.homeDirectory ?? os.homedir())}`,
    `Environment=VITE_LOCAL_TLS_RUNTIME_DIRECTORY=${systemdQuote(options.paths.runtimeDirectory)}`,
    `ExecStart=${arguments_.map(systemdQuote).join(' ')}`,
    'Restart=on-failure',
    'RestartSec=1',
    'AmbientCapabilities=CAP_NET_BIND_SERVICE',
    'CapabilityBoundingSet=CAP_NET_BIND_SERVICE',
    'NoNewPrivileges=true',
    'PrivateTmp=false',
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    '',
  ].join('\n');
}

export function usesSudo(options: ServiceInstallOptions): boolean {
  return options.useSudo === true || (options.useSudo !== false && process.getuid?.() !== 0);
}

export function runElevatedCommand(
  options: ServiceInstallOptions,
  runner: ServiceInstallCommandRunner,
  command: string,
  arguments_: string[],
  timeoutMs?: number,
): Promise<ServiceInstallCommandResult> {
  const useSudo = usesSudo(options);
  if (!useSudo) {
    return timeoutMs ? runner(command, arguments_, { timeoutMs }) : runner(command, arguments_);
  }
  return runner('sudo', ['--', command, ...arguments_], {
    interactive: true,
    ...(timeoutMs ? { timeoutMs } : {}),
  });
}

export async function runElevatedCommands(
  options: ServiceInstallOptions,
  runner: ServiceInstallCommandRunner,
  commands: ServiceInstallElevatedCommand[],
): Promise<void> {
  if ((options.platform ?? process.platform) === 'darwin' && usesSudo(options) && !process.env.CI) {
    await runner('/usr/bin/osascript', [
      '-e',
      'on run argv',
      '-e',
      'set commandPath to quoted form of (item 1 of argv)',
      '-e',
      'set source to quoted form of (item 2 of argv)',
      '-e',
      'set requests to quoted form of (item 3 of argv)',
      '-e',
      'do shell script (commandPath & " --input-type=module --eval " & source & " " & requests) with administrator privileges with prompt "Vite Local TLS needs permission to install or update its local HTTPS service."',
      '-e',
      'end run',
      process.execPath,
      MACOS_ELEVATED_SEQUENCE_SOURCE,
      JSON.stringify(commands),
    ]);
    return;
  }
  const rollback: ServiceInstallElevatedCommand[][] = [];
  for (const request of commands) {
    try {
      await runElevatedCommand(
        options,
        runner,
        request.command,
        request.arguments_,
        request.timeoutMs,
      );
      if (request.clearRollbackAfterSuccess) {
        rollback.length = 0;
      }
      if (request.discardRollbackAfterSuccess) {
        rollback.pop();
      }
      if (request.rollbackAfterSuccess?.length) {
        rollback.push(request.rollbackAfterSuccess);
      }
    } catch (error) {
      if (!request.allowFailure) {
        let rollbackFailed = false;
        for (const group of [...rollback].reverse()) {
          for (const recovery of group) {
            try {
              await runElevatedCommand(
                options,
                runner,
                recovery.command,
                recovery.arguments_,
                recovery.timeoutMs,
              );
            } catch {
              if (!recovery.allowFailure) {
                rollbackFailed = true;
                break;
              }
            }
          }
          if (rollbackFailed) {
            break;
          }
        }
        throw error;
      }
    }
  }
}

export async function inspectRunningInstallations(
  installations: ObsoleteServiceInstallation[],
): Promise<ObsoleteServiceInstallation[]> {
  return Promise.all(
    installations.map(async (item) => ({
      ...item,
      wasRunning: (await installedService(item.installation).status()).running,
    })),
  );
}
