import { execFile } from 'node:child_process';
import { mkdir, readFile, rename, unlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import type {
  ServiceInstallCommandResult,
  ServiceInstallCommandRunner,
  ServiceInstallationRecord,
  ServiceInstallOptions,
  ServiceInstallResult,
} from './interfaces/service-install-options.js';
import { ensureStatePaths, sanitizeNamespace } from './state-paths.js';

const OWNER_MARKER = 'generated by @vampaz/vite-plugin-local-tls';

function runCommand(command: string, arguments_: string[]): Promise<ServiceInstallCommandResult> {
  return new Promise((resolve, reject) => {
    execFile(command, arguments_, { maxBuffer: 10 * 1024 * 1024 }, (error, stdout, stderr) => {
      if (error) {
        reject(new Error(stderr.trim() || error.message, { cause: error }));
        return;
      }
      resolve({ stdout, stderr });
    });
  });
}

function xmlEscape(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

function systemdQuote(value: string): string {
  return `"${value.replaceAll('%', '%%').replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;
}

function windowsQuote(value: string): string {
  return `"${value.replaceAll(/(\\*)"/g, '$1$1\\"').replaceAll(/(\\+)$/g, '$1$1')}"`;
}

function validateDefinitionValue(value: string, label: string): string {
  const hasControlCharacter = [...value].some((character) => {
    const codePoint = character.codePointAt(0) ?? 0;
    return codePoint < 32 || codePoint === 127;
  });
  if (!value || hasControlCharacter) {
    throw new Error(`${label} contains unsupported control characters.`);
  }
  return value;
}

function safeServiceKey(options: ServiceInstallOptions): string {
  const key = sanitizeNamespace(options.namespace);
  if (!/^[a-z0-9-]{1,40}$/.test(key)) {
    throw new Error(`Unsafe service namespace: ${key}`);
  }
  validateDefinitionValue(options.namespace, 'Service namespace');
  validateDefinitionValue(options.nodePath, 'Node path');
  validateDefinitionValue(options.cliPath, 'CLI path');
  if (options.controlSocket) {
    validateDefinitionValue(options.controlSocket, 'Control socket');
  }
  return key;
}

function recordPath(options: ServiceInstallOptions): string {
  return path.join(options.paths.stateDirectory, 'service-install.json');
}

async function readRecord(
  options: ServiceInstallOptions,
): Promise<ServiceInstallationRecord | null> {
  try {
    const record = JSON.parse(
      await readFile(recordPath(options), 'utf8'),
    ) as ServiceInstallationRecord;
    if (
      record.version !== 1 ||
      record.namespace !== options.namespace ||
      record.platform !== (options.platform ?? process.platform)
    ) {
      throw new Error('Service installation record does not match this namespace and platform.');
    }
    return record;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return null;
    }
    throw error;
  }
}

async function writeRecord(
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
): Promise<void> {
  const finalPath = recordPath(options);
  const temporaryPath = `${finalPath}.${process.pid}.tmp`;
  await writeFile(temporaryPath, `${JSON.stringify(record, null, 2)}\n`, { mode: 0o600 });
  await rename(temporaryPath, finalPath);
}

async function assertOwnedDefinition(definitionPath: string): Promise<void> {
  try {
    const contents = await readFile(definitionPath, 'utf8');
    if (!contents.includes(OWNER_MARKER)) {
      throw new Error(`Refusing to overwrite unrelated service definition: ${definitionPath}`);
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
  }
}

function launchdDefinition(options: ServiceInstallOptions, identifier: string): string {
  const arguments_ = [
    options.nodePath,
    options.cliPath,
    'proxy',
    'start',
    '--service',
    '--namespace',
    options.namespace,
  ];
  if (options.controlSocket) {
    arguments_.push('--control-socket', options.controlSocket);
  }
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    '<dict>',
    `  <!-- ${OWNER_MARKER} -->`,
    '  <key>Label</key>',
    `  <string>${xmlEscape(identifier)}</string>`,
    '  <key>ProgramArguments</key>',
    '  <array>',
    ...arguments_.map((argument) => `    <string>${xmlEscape(argument)}</string>`),
    '  </array>',
    '  <key>RunAtLoad</key>',
    '  <true/>',
    '  <key>KeepAlive</key>',
    '  <true/>',
    '  <key>ProcessType</key>',
    '  <string>Background</string>',
    '  <key>StandardOutPath</key>',
    `  <string>${xmlEscape(path.join(options.paths.stateDirectory, 'service.log'))}</string>`,
    '  <key>StandardErrorPath</key>',
    `  <string>${xmlEscape(path.join(options.paths.stateDirectory, 'service-error.log'))}</string>`,
    '</dict>',
    '</plist>',
    '',
  ].join('\n');
}

function systemdDefinition(options: ServiceInstallOptions): string {
  const username = options.username ?? os.userInfo().username;
  const arguments_ = [
    options.nodePath,
    options.cliPath,
    'proxy',
    'start',
    '--service',
    '--namespace',
    options.namespace,
  ];
  if (options.controlSocket) {
    arguments_.push('--control-socket', options.controlSocket);
  }
  const writablePaths = [options.paths.stateDirectory, options.paths.runtimeDirectory];
  if (options.controlSocket && !options.controlSocket.startsWith('\\\\.\\pipe\\')) {
    writablePaths.push(path.dirname(options.controlSocket));
  }
  return [
    `# ${OWNER_MARKER}`,
    '[Unit]',
    'Description=Vite local TLS proxy',
    'After=network.target',
    '',
    '[Service]',
    'Type=simple',
    `User=${username}`,
    `Environment=HOME=${systemdQuote(options.homeDirectory ?? os.homedir())}`,
    `ExecStart=${arguments_.map(systemdQuote).join(' ')}`,
    'Restart=on-failure',
    'RestartSec=1',
    'AmbientCapabilities=CAP_NET_BIND_SERVICE',
    'CapabilityBoundingSet=CAP_NET_BIND_SERVICE',
    'NoNewPrivileges=true',
    'ProtectSystem=strict',
    `ReadWritePaths=${writablePaths.map(systemdQuote).join(' ')}`,
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    '',
  ].join('\n');
}

function elevatedRunner(options: ServiceInstallOptions): {
  command: string;
  arguments_: (command: string, arguments_: string[]) => string[];
} {
  const useSudo =
    options.useSudo === true || (options.useSudo !== false && process.getuid?.() !== 0);
  return useSudo
    ? { command: 'sudo', arguments_: (command, arguments_) => ['--', command, ...arguments_] }
    : { command: '', arguments_: (_command, arguments_) => arguments_ };
}

async function installMacos(
  options: ServiceInstallOptions,
  runner: ServiceInstallCommandRunner,
  identifier: string,
): Promise<string> {
  const homeDirectory = options.homeDirectory ?? os.homedir();
  const definitionPath = path.join(homeDirectory, 'Library', 'LaunchAgents', `${identifier}.plist`);
  await mkdir(path.dirname(definitionPath), { recursive: true, mode: 0o700 });
  await assertOwnedDefinition(definitionPath);
  await writeFile(definitionPath, launchdDefinition(options, identifier), { mode: 0o600 });
  const domain = `gui/${options.uid ?? process.getuid?.() ?? os.userInfo().uid}`;
  await runner('launchctl', ['bootout', domain, definitionPath]).catch(() => undefined);
  await runner('launchctl', ['bootstrap', domain, definitionPath]);
  await runner('launchctl', ['enable', `${domain}/${identifier}`]);
  await runner('launchctl', ['kickstart', '-k', `${domain}/${identifier}`]);
  return definitionPath;
}

async function installLinux(
  options: ServiceInstallOptions,
  runner: ServiceInstallCommandRunner,
  identifier: string,
): Promise<string> {
  const definitionPath = path.join(
    options.definitionDirectory ?? '/etc/systemd/system',
    `${identifier}.service`,
  );
  await assertOwnedDefinition(definitionPath);
  const temporaryPath = path.join(options.paths.stateDirectory, `${identifier}.service.tmp`);
  await writeFile(temporaryPath, systemdDefinition(options), { mode: 0o600 });
  const elevated = elevatedRunner(options);
  const runElevated = async function runElevated(
    command: string,
    arguments_: string[],
  ): Promise<ServiceInstallCommandResult> {
    return runner(
      elevated.command || command,
      elevated.command ? elevated.arguments_(command, arguments_) : arguments_,
    );
  };
  try {
    await runElevated('install', ['-m', '0644', '--', temporaryPath, definitionPath]);
    await runElevated('systemctl', ['daemon-reload']);
    await runElevated('systemctl', ['enable', '--now', `${identifier}.service`]);
  } finally {
    await unlink(temporaryPath).catch(() => undefined);
  }
  return definitionPath;
}

async function windowsTaskExists(
  runner: ServiceInstallCommandRunner,
  identifier: string,
): Promise<boolean> {
  return runner('schtasks.exe', ['/Query', '/TN', identifier])
    .then(() => true)
    .catch(() => false);
}

async function installWindows(
  options: ServiceInstallOptions,
  runner: ServiceInstallCommandRunner,
  identifier: string,
): Promise<void> {
  if (!(await readRecord(options)) && (await windowsTaskExists(runner, identifier))) {
    throw new Error(`Refusing to replace unrelated scheduled task: ${identifier}`);
  }
  const command = [
    windowsQuote(options.nodePath),
    windowsQuote(options.cliPath),
    'proxy',
    'start',
    '--service',
    '--namespace',
    windowsQuote(options.namespace),
  ].join(' ');
  const controlSocket = options.controlSocket
    ? ` --control-socket ${windowsQuote(options.controlSocket)}`
    : '';
  await runner('schtasks.exe', [
    '/Create',
    '/TN',
    identifier,
    '/TR',
    `${command}${controlSocket}`,
    '/SC',
    'ONLOGON',
    '/RL',
    'LIMITED',
    '/F',
  ]);
  await runner('schtasks.exe', ['/Run', '/TN', identifier]);
}

export async function installStartupService(
  options: ServiceInstallOptions,
): Promise<ServiceInstallResult> {
  await ensureStatePaths(options.paths);
  const platform = options.platform ?? process.platform;
  const key = safeServiceKey(options);
  const runner = options.runner ?? runCommand;
  const identifier =
    platform === 'darwin'
      ? `com.vampaz.vite-local-tls.${key}`
      : platform === 'win32'
        ? `Vite Local TLS\\${key}`
        : `vite-local-tls-${key}`;
  let definitionPath: string | null = null;
  if (platform === 'darwin') {
    definitionPath = await installMacos(options, runner, identifier);
  } else if (platform === 'linux') {
    definitionPath = await installLinux(options, runner, identifier);
  } else if (platform === 'win32') {
    await installWindows(options, runner, identifier);
  } else {
    throw new Error(`Unsupported service platform: ${platform}`);
  }
  const record: ServiceInstallationRecord = {
    version: 1,
    platform,
    namespace: options.namespace,
    identifier,
    definitionPath,
    nodePath: options.nodePath,
    cliPath: options.cliPath,
    controlSocket: options.controlSocket ?? null,
    installedAt: new Date().toISOString(),
  };
  await writeRecord(options, record);
  return { installed: true, record };
}

export async function uninstallStartupService(
  options: ServiceInstallOptions,
): Promise<ServiceInstallResult> {
  const record = await readRecord(options);
  if (!record) {
    return { installed: false, record: null };
  }
  const runner = options.runner ?? runCommand;
  if (record.platform === 'darwin') {
    const domain = `gui/${options.uid ?? process.getuid?.() ?? os.userInfo().uid}`;
    await runner('launchctl', ['bootout', domain, record.definitionPath!]).catch(() => undefined);
    await assertOwnedDefinition(record.definitionPath!);
    await unlink(record.definitionPath!);
  } else if (record.platform === 'linux') {
    await assertOwnedDefinition(record.definitionPath!);
    const elevated = elevatedRunner(options);
    async function runElevated(command: string, arguments_: string[]): Promise<void> {
      await runner(
        elevated.command || command,
        elevated.command ? elevated.arguments_(command, arguments_) : arguments_,
      );
    }
    await runElevated('systemctl', ['disable', '--now', `${record.identifier}.service`]);
    await runElevated('rm', ['-f', '--', record.definitionPath!]);
    await runElevated('systemctl', ['daemon-reload']);
  } else if (record.platform === 'win32') {
    const task = await runner('schtasks.exe', ['/Query', '/TN', record.identifier, '/XML']);
    const ownsTask = [record.nodePath, record.cliPath, '--service', record.namespace].every(
      (value) => task.stdout.includes(value) || task.stdout.includes(xmlEscape(value)),
    );
    if (!ownsTask) {
      throw new Error(`Refusing to remove unrelated scheduled task: ${record.identifier}`);
    }
    await runner('schtasks.exe', ['/End', '/TN', record.identifier]).catch(() => undefined);
    await runner('schtasks.exe', ['/Delete', '/TN', record.identifier, '/F']);
  }
  await unlink(recordPath(options));
  return { installed: false, record };
}
