import { access, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { StatePaths } from './interfaces/state-paths.js';
import { installStartupService, uninstallStartupService } from './service-install.js';

let temporaryDirectory: string;

function statePaths(): StatePaths {
  const stateDirectory = path.join(temporaryDirectory, 'state');
  const runtimeDirectory = path.join(temporaryDirectory, 'runtime', 'test');
  return {
    stateDirectory,
    runtimeDirectory,
    socketPath: path.join(runtimeDirectory, 'control.sock'),
    lockPath: path.join(runtimeDirectory, 'startup.lock'),
    stateFile: path.join(stateDirectory, 'service.json'),
    certificateDirectory: path.join(stateDirectory, 'certificates'),
    importedCertificateDirectory: path.join(stateDirectory, 'imported'),
    caKeyPath: path.join(stateDirectory, 'ca-key.pem'),
    caCertificatePath: path.join(stateDirectory, 'ca.pem'),
    caStatePath: path.join(stateDirectory, 'ca.json'),
  };
}

beforeEach(async () => {
  temporaryDirectory = await mkdtemp(path.join(os.tmpdir(), 'vite-local-tls-launchd-'));
});

afterEach(async () => {
  await rm(temporaryDirectory, { recursive: true, force: true });
});

describe('macOS startup service', () => {
  it('installs and removes only its user launch agent without elevation', async () => {
    const runner = vi.fn(async (_command: string, _arguments: string[]) => ({
      stdout: '',
      stderr: '',
    }));
    const options = {
      platform: 'darwin' as const,
      namespace: 'test',
      paths: statePaths(),
      nodePath: '/opt/homebrew/bin/node',
      cliPath: '/project/dist/cli.js',
      homeDirectory: temporaryDirectory,
      uid: 501,
      runner,
    };

    const installed = await installStartupService(options);
    const definitionPath = installed.record?.definitionPath ?? '';
    const definition = await readFile(definitionPath, 'utf8');

    expect(definition).toContain('generated by @vampaz/vite-plugin-local-tls');
    expect(definition).toContain('<string>/opt/homebrew/bin/node</string>');
    expect(definition).toContain('<string>--service</string>');
    expect(definition).toContain('<string>--namespace</string>');
    expect(runner).toHaveBeenCalledWith('launchctl', ['bootstrap', 'gui/501', definitionPath]);
    expect(runner.mock.calls.some(([command]) => command === 'sudo')).toBe(false);

    await uninstallStartupService(options);

    await expect(access(definitionPath)).rejects.toThrow();
    expect(runner).toHaveBeenCalledWith('launchctl', ['bootout', 'gui/501', definitionPath]);
  });

  it('refuses to overwrite an unrelated definition at the same path', async () => {
    const runner = vi.fn(async (_command: string, _arguments: string[]) => ({
      stdout: '',
      stderr: '',
    }));
    const options = {
      platform: 'darwin' as const,
      namespace: 'test',
      paths: statePaths(),
      nodePath: '/usr/bin/node',
      cliPath: '/project/dist/cli.js',
      homeDirectory: temporaryDirectory,
      runner,
    };
    await installStartupService(options);
    const definitionPath = path.join(
      temporaryDirectory,
      'Library',
      'LaunchAgents',
      'com.vampaz.vite-local-tls.test.plist',
    );
    await writeFile(definitionPath, '<plist>unrelated</plist>');

    await expect(installStartupService(options)).rejects.toThrow(/unrelated service definition/);
  });
});
