import { createHash, randomUUID } from 'node:crypto';
import {
  chmod,
  copyFile,
  lstat,
  mkdir,
  readFile,
  rename,
  rm,
  unlink,
  writeFile,
} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import type {
  ServiceInstallCommandResult,
  ServiceInstallCommandRunner,
  ServiceInstallElevatedCommand,
  ServiceInstallationRecord,
  ServiceInstallOptions,
  ServiceInstallResult,
  StartupServiceUpdateStatus,
} from './interfaces/service-install-options.js';
import type { ServiceRuntimeConfiguration } from './interfaces/service-runtime-configuration.js';
import { executeCommand } from './command-runner.js';
import { CONTROL_PROTOCOL_VERSION } from './control-protocol.js';
import { PACKAGE_VERSION } from './package-version.js';
import { LocalTlsService } from './service.js';
import { compareServiceVersions } from './service-version.js';
import { ensureStatePaths, sanitizeNamespace } from './state-paths.js';

const LEGACY_STARTUP_SERVICE_OWNER_MARKER = 'generated by @vampaz/vite-plugin-local-tls';
export const STARTUP_SERVICE_OWNER_MARKER =
  'managed startup-service-v2 by @vampaz/vite-plugin-local-tls';
const OWNER_MARKER = STARTUP_SERVICE_OWNER_MARKER;
export const CANONICAL_SERVICE_NAMESPACE = 'default';
const MACOS_ELEVATED_SEQUENCE_SOURCE = [
  'import { spawnSync } from "node:child_process";',
  'const commands = JSON.parse(process.argv[1]);',
  'const rollback = [];',
  'for (const request of commands) {',
  '  const child = spawnSync(request.command, request.arguments_, { stdio: "inherit", timeout: request.timeoutMs ?? 15_000 });',
  '  if (child.error) console.error(child.error.message);',
  '  if (child.error || child.status !== 0) {',
  '    if (request.allowFailure) continue;',
  '    rollback: for (const group of [...rollback].reverse()) {',
  '      for (const recovery of group) {',
  '        const restored = spawnSync(recovery.command, recovery.arguments_, { stdio: "inherit", timeout: recovery.timeoutMs ?? 15_000 });',
  '        if ((restored.error || restored.status !== 0) && !recovery.allowFailure) break rollback;',
  '      }',
  '    }',
  '    process.exit(child.status ?? 1);',
  '  }',
  '  if (request.clearRollbackAfterSuccess) rollback.length = 0;',
  '  if (request.discardRollbackAfterSuccess) rollback.pop();',
  '  if (request.rollbackAfterSuccess?.length) rollback.push(request.rollbackAfterSuccess);',
  '}',
].join('\n');

const MACOS_LAUNCHD_REMOVAL_WAIT_SOURCE = [
  'import { spawnSync } from "node:child_process";',
  'const identifier = process.argv[1];',
  'const deadline = Date.now() + 10_000;',
  'let absentChecks = 0;',
  'while (Date.now() < deadline) {',
  '  const child = spawnSync("launchctl", ["print", `system/${identifier}`], { stdio: "ignore" });',
  '  if (child.error) { console.error(child.error.message); process.exit(1); }',
  '  absentChecks = child.status === 0 ? 0 : absentChecks + 1;',
  '  if (absentChecks === 2) process.exit(0);',
  '  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 100);',
  '}',
  'console.error(`Timed out waiting for launchd to remove ${identifier}.`);',
  'process.exit(1);',
].join('\n');

const MACOS_SERVICE_READINESS_WAIT_SOURCE = [
  'import { spawnSync } from "node:child_process";',
  'const [nodePath, cliPath, namespace, controlSocket] = process.argv.slice(1);',
  'const deadline = Date.now() + 30_000;',
  'let lastStatus = "no status response";',
  'while (Date.now() < deadline) {',
  '  const child = spawnSync(nodePath, [cliPath, "proxy", "status", "--namespace", namespace, "--control-socket", controlSocket], { encoding: "utf8", timeout: 2_000 });',
  '  lastStatus = child.error?.message || child.stderr?.trim() || child.stdout?.trim() || `exit ${child.status}`;',
  '  if (!child.error && child.status === 0) {',
  '    try {',
  '      const status = JSON.parse(child.stdout);',
  '      if (status.running === true && status.compatible === true) process.exit(0);',
  '    } catch {}',
  '  }',
  '  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 100);',
  '}',
  'console.error(`Timed out waiting for the installed local TLS service: ${lastStatus}`);',
  'process.exit(1);',
].join('\n');

interface ObsoleteServiceInstallation {
  installation: ServiceInstallOptions;
  record: ServiceInstallationRecord;
  wasRunning?: boolean;
}

interface MacosControlClient {
  nodePath: string;
  cliPath: string;
}

function xmlEscape(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

function systemdQuote(value: string): string {
  return `"${value.replaceAll('%', '%%').replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;
}

function linuxUserRuntimeUnit(options: ServiceInstallOptions): string | null {
  const match = /^\/run\/user\/(\d+)(?:\/|$)/.exec(options.paths.runtimeDirectory);
  if (!match) {
    return null;
  }
  const runtimeUid = Number(match[1]);
  const uid = options.uid ?? process.getuid?.() ?? os.userInfo().uid;
  if (!Number.isSafeInteger(runtimeUid) || runtimeUid !== uid) {
    throw new Error('The Linux runtime directory does not belong to the installing user.');
  }
  return `user-runtime-dir@${uid}.service`;
}

function xmlDecode(value: string): string | null {
  if (/&(?!amp;|apos;|gt;|lt;|quot;|#\d+;|#x[\dA-Fa-f]+;)/.test(value)) {
    return null;
  }
  return value.replace(/&(amp|apos|gt|lt|quot|#\d+|#x[\dA-Fa-f]+);/g, (_match, entity: string) => {
    if (entity === 'amp') return '&';
    if (entity === 'apos') return "'";
    if (entity === 'gt') return '>';
    if (entity === 'lt') return '<';
    if (entity === 'quot') return '"';
    const codePoint = Number.parseInt(
      entity.slice(entity[1] === 'x' ? 2 : 1),
      entity[1] === 'x' ? 16 : 10,
    );
    return Number.isSafeInteger(codePoint) && codePoint <= 0x10ffff
      ? String.fromCodePoint(codePoint)
      : '\uFFFD';
  });
}

function xmlWithoutComments(contents: string): string {
  return contents.replaceAll(/<!--[\s\S]*?-->/g, '');
}

function singleXmlElement(contents: string, element: string): string | null {
  const expression = new RegExp(`<${element}>([\\s\\S]*?)</${element}>`, 'g');
  const matches = [...contents.matchAll(expression)];
  return matches.length === 1 ? xmlDecode(matches[0]![1]!) : null;
}

function singleXmlContainer(contents: string, element: string): string | null {
  const expression = new RegExp(`<${element}(?:\\s[^>]*)?>([\\s\\S]*?)</${element}>`, 'g');
  const matches = [...contents.matchAll(expression)];
  return matches.length === 1 ? matches[0]![1]! : null;
}

function ownerMarker(record: ServiceInstallationRecord): string {
  return record.version === 1 ? LEGACY_STARTUP_SERVICE_OWNER_MARKER : OWNER_MARKER;
}

function normalizeXmlDefinition(contents: string): string {
  return xmlWithoutComments(contents).replaceAll(/>\s+</g, '><').trim();
}

function normalizeSystemdDefinition(contents: string): string[] {
  return contents
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#') && !line.startsWith(';'));
}

export function serviceDefinitionMatchesInstallation(
  contents: string,
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
): boolean {
  if (record.platform === 'darwin') {
    const expected = launchdDefinition(
      {
        ...options,
        nodePath: record.nodePath,
        cliPath: record.cliPath,
        controlSocket: record.controlSocket ?? undefined,
      },
      record.identifier,
      record.version,
    );
    return (
      contents.includes(`<!-- ${ownerMarker(record)} -->`) &&
      normalizeXmlDefinition(contents) === normalizeXmlDefinition(expected)
    );
  }
  if (record.platform === 'linux') {
    const expected = systemdDefinition(
      {
        ...options,
        nodePath: record.nodePath,
        cliPath: record.cliPath,
        controlSocket: record.controlSocket ?? undefined,
      },
      record.version,
    );
    return (
      contents.split(/\r?\n/).some((line) => line.trim() === `# ${ownerMarker(record)}`) &&
      JSON.stringify(normalizeSystemdDefinition(contents)) ===
        JSON.stringify(normalizeSystemdDefinition(expected))
    );
  }
  return record.platform === 'win32';
}

function windowsQuote(value: string): string {
  return `"${value.replaceAll(/(\\*)"/g, '$1$1\\"').replaceAll(/(\\+)$/g, '$1$1')}"`;
}

function validateDefinitionValue(value: string, label: string): string {
  const hasControlCharacter = [...value].some((character) => {
    const codePoint = character.codePointAt(0) ?? 0;
    return codePoint < 32 || codePoint === 127;
  });
  if (!value || hasControlCharacter) {
    throw new Error(`${label} contains unsupported control characters.`);
  }
  return value;
}

function safeServiceKey(options: ServiceInstallOptions): string {
  const platform = options.platform ?? process.platform;
  const key = sanitizeNamespace(options.namespace);
  if (!/^[a-z0-9-]{1,40}$/.test(key)) {
    throw new Error(`Unsafe service namespace: ${key}`);
  }
  validateDefinitionValue(options.namespace, 'Service namespace');
  if (options.namespace.length > 256) {
    throw new Error('Service namespace exceeds 256 characters.');
  }
  validateDefinitionValue(options.nodePath, 'Node path');
  validateDefinitionValue(options.cliPath, 'CLI path');
  validateDefinitionValue(options.homeDirectory ?? os.homedir(), 'Home directory');
  validateDefinitionValue(options.username ?? os.userInfo().username, 'Username');
  validateDefinitionValue(options.paths.stateDirectory, 'State directory');
  validateDefinitionValue(options.paths.runtimeDirectory, 'Runtime directory');
  validateDefinitionValue(options.paths.socketPath, 'Control socket');
  if (options.controlSocket) {
    validateDefinitionValue(options.controlSocket, 'Control socket');
    if (options.controlSocket.length > 4096) {
      throw new Error('Control socket exceeds 4096 characters.');
    }
  }
  if (options.runtimeInstallDirectory) {
    validateDefinitionValue(options.runtimeInstallDirectory, 'Service runtime directory');
  }
  if (
    platform === 'linux' &&
    !/^[a-zA-Z_][a-zA-Z0-9_-]*\$?$/.test(options.username ?? os.userInfo().username)
  ) {
    throw new Error('Username cannot be represented safely in a systemd service.');
  }
  if (platform === 'darwin') {
    for (const [label, value] of [
      ['User ID', options.uid ?? os.userInfo().uid],
      ['Group ID', options.gid ?? os.userInfo().gid],
    ] as const) {
      if (!Number.isSafeInteger(value) || value < 0) {
        throw new Error(`${label} must be a non-negative integer.`);
      }
    }
  }
  return key;
}

function recordPath(options: ServiceInstallOptions, version: 1 | 2): string {
  return path.join(
    options.paths.stateDirectory,
    version === 2 ? 'service-install-v2.json' : 'service-install.json',
  );
}

function previousRecordPath(options: ServiceInstallOptions): string {
  return path.join(options.paths.stateDirectory, 'service-install-previous.json');
}

async function removeInstallationRecords(options: ServiceInstallOptions): Promise<void> {
  await Promise.all(
    [recordPath(options, 1), recordPath(options, 2), previousRecordPath(options)].map((filePath) =>
      unlink(filePath).catch((error: NodeJS.ErrnoException) => {
        if (error.code !== 'ENOENT') {
          throw error;
        }
      }),
    ),
  );
}

export function serviceIdentifier(platform: NodeJS.Platform, key: string): string {
  return platform === 'darwin'
    ? `com.vampaz.vite-local-tls.${key}`
    : platform === 'win32'
      ? `Vite Local TLS\\${key}`
      : `vite-local-tls-${key}`;
}

export function expectedDefinitionPath(
  options: ServiceInstallOptions,
  platform: NodeJS.Platform,
  identifier: string,
): string | null {
  if (platform === 'darwin') {
    return path.join(
      options.definitionDirectory ?? '/Library/LaunchDaemons',
      `${identifier}.plist`,
    );
  }
  if (platform === 'linux') {
    return path.join(options.definitionDirectory ?? '/etc/systemd/system', `${identifier}.service`);
  }
  return null;
}

export function expectedRuntimeDirectory(
  options: ServiceInstallOptions,
  platform: NodeJS.Platform,
  key: string,
): string {
  if (options.runtimeInstallDirectory) {
    return options.runtimeInstallDirectory;
  }
  if (platform === 'darwin') {
    return path.join('/Library/Application Support/vite-plugin-local-tls', key);
  }
  if (platform === 'win32') {
    return path.join(
      path.dirname(path.dirname(options.paths.stateDirectory)),
      'vlt',
      windowsRuntimeKey(key),
    );
  }
  return path.join(options.paths.stateDirectory, 'service-runtime');
}

function windowsConfigurationPath(runtimeDirectory: string): string {
  return path.join(runtimeDirectory, 's.json');
}

function windowsRuntimeKey(key: string): string {
  return createHash('sha256').update(key).digest('hex').slice(0, 12);
}

function windowsTaskPath(filePath: string): string {
  const localAppData = process.env.LOCALAPPDATA;
  if (!localAppData) {
    return filePath;
  }
  const relativePath = path.win32.relative(localAppData, filePath);
  if (relativePath.startsWith('..') || path.win32.isAbsolute(relativePath)) {
    return filePath;
  }
  return path.win32.join('%LOCALAPPDATA%', relativePath);
}

function windowsTaskCommand(nodePath: string, cliPath: string, configurationPath: string): string {
  return `${windowsQuote(windowsTaskPath(nodePath))} ${windowsTaskArguments(
    cliPath,
    configurationPath,
  )}`;
}

function windowsTaskArgumentsForPaths(cliPath: string, configurationPath: string): string {
  return [
    windowsQuote(cliPath),
    'proxy',
    'start',
    '--service',
    '--service-config',
    windowsQuote(configurationPath),
  ].join(' ');
}

function windowsTaskArguments(cliPath: string, configurationPath: string): string {
  return windowsTaskArgumentsForPaths(windowsTaskPath(cliPath), windowsTaskPath(configurationPath));
}

function windowsTaskPathCandidates(filePath: string): string[] {
  return [...new Set([windowsTaskPath(filePath), filePath])];
}

function windowsTaskArgumentCandidates(cliPath: string, configurationPath: string): string[] {
  return windowsTaskPathCandidates(cliPath).flatMap((taskCliPath) =>
    windowsTaskPathCandidates(configurationPath).map((taskConfigurationPath) =>
      windowsTaskArgumentsForPaths(taskCliPath, taskConfigurationPath),
    ),
  );
}

function assertExpectedRecord(
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
): void {
  const platform = options.platform ?? process.platform;
  const key = safeServiceKey(options);
  const identifier = serviceIdentifier(platform, key);
  const definitionPath = expectedDefinitionPath(options, platform, identifier);
  if (record.identifier !== identifier || record.definitionPath !== definitionPath) {
    throw new Error('Service installation record contains unexpected system targets.');
  }
  const runtimeDirectory = expectedRuntimeDirectory(options, platform, key);
  const cliPath = path.join(
    runtimeDirectory,
    platform === 'darwin' ? 'cli.js' : platform === 'win32' ? 'c.js' : `cli-${key}.js`,
  );
  const nodePath = path.join(runtimeDirectory, platform === 'win32' ? 'n.exe' : 'node');
  if (
    record.runtimeDirectory !== runtimeDirectory ||
    record.cliPath !== cliPath ||
    record.nodePath !== nodePath
  ) {
    throw new Error('Service installation record contains an unexpected runtime target.');
  }
}

async function readRegularInstallationRecord(filePath: string): Promise<string> {
  const details = await lstat(filePath);
  if (!details.isFile() || details.isSymbolicLink()) {
    throw new Error(`Refusing unsafe service installation record: ${filePath}`);
  }
  return readFile(filePath, 'utf8');
}

async function readRecord(
  options: ServiceInstallOptions,
): Promise<ServiceInstallationRecord | null> {
  let contents: string;
  let recordVersion: 1 | 2 | null = 2;
  let recoveredPreviousRecord = false;
  try {
    contents = await readRegularInstallationRecord(recordPath(options, 2));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
    recordVersion = 1;
    try {
      contents = await readRegularInstallationRecord(recordPath(options, 1));
    } catch (legacyError) {
      if ((legacyError as NodeJS.ErrnoException).code !== 'ENOENT') {
        throw legacyError;
      }
      try {
        contents = await readRegularInstallationRecord(previousRecordPath(options));
        recordVersion = null;
        recoveredPreviousRecord = true;
      } catch (previousError) {
        if ((previousError as NodeJS.ErrnoException).code === 'ENOENT') {
          return null;
        }
        throw previousError;
      }
    }
  }
  const record = JSON.parse(contents) as ServiceInstallationRecord;
  if (
    (recordVersion !== null && record.version !== recordVersion) ||
    (record.version !== 1 && record.version !== 2) ||
    record.namespace !== options.namespace ||
    record.platform !== (options.platform ?? process.platform) ||
    (record.version === 2 &&
      (typeof record.packageVersion !== 'string' ||
        !Number.isInteger(record.protocolVersion) ||
        record.protocolVersion < 1 ||
        (record.installationState !== 'installing' && record.installationState !== 'installed') ||
        (recoveredPreviousRecord && record.installationState !== 'installed')))
  ) {
    throw new Error('Service installation record does not match this namespace and platform.');
  }
  assertExpectedRecord(options, record);
  return record;
}

async function readPreviousRecord(
  options: ServiceInstallOptions,
): Promise<ServiceInstallationRecord | null> {
  let contents: string;
  try {
    contents = await readRegularInstallationRecord(previousRecordPath(options));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return null;
    }
    throw error;
  }
  const record = JSON.parse(contents) as ServiceInstallationRecord;
  if (
    (record.version !== 1 && record.version !== 2) ||
    record.namespace !== options.namespace ||
    record.platform !== (options.platform ?? process.platform) ||
    (record.version === 2 &&
      (typeof record.packageVersion !== 'string' ||
        !Number.isInteger(record.protocolVersion) ||
        record.protocolVersion < 1 ||
        record.installationState !== 'installed'))
  ) {
    throw new Error('Previous service installation record is invalid.');
  }
  assertExpectedRecord(options, record);
  return record;
}

export async function getStartupServiceUpdateStatus(
  options: ServiceInstallOptions,
): Promise<StartupServiceUpdateStatus> {
  const record = await readRecord(options);
  if (!record) {
    return 'absent';
  }
  if (record.version === 1) {
    return 'legacy';
  }
  if (record.installationState !== 'installed') {
    return 'installing';
  }
  const versionComparison = compareServiceVersions(
    record.packageVersion,
    options.currentVersion ?? PACKAGE_VERSION,
  );
  if (versionComparison === null) {
    return 'modified';
  }
  if (versionComparison === 1) {
    return record.protocolVersion === CONTROL_PROTOCOL_VERSION ? 'newer' : 'newer-incompatible';
  }
  if (versionComparison === -1) {
    return 'outdated';
  }
  if (record.protocolVersion !== CONTROL_PROTOCOL_VERSION) {
    return 'modified';
  }
  if (record.controlSocket !== (options.controlSocket ?? null)) {
    return 'modified';
  }
  try {
    const [currentCli, installedCli] = await Promise.all([
      readFile(options.cliPath),
      readFile(record.cliPath),
    ]);
    return currentCli.equals(installedCli) ? 'current' : 'modified';
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return 'modified';
    }
    throw error;
  }
}

export async function isStartupServiceCurrent(options: ServiceInstallOptions): Promise<boolean> {
  return ['absent', 'current', 'newer'].includes(await getStartupServiceUpdateStatus(options));
}

function installedService(options: ServiceInstallOptions): LocalTlsService {
  return new LocalTlsService({
    paths: options.paths,
    opensslPath: 'openssl',
    namespace: options.namespace,
    port: 443,
  });
}

function optionsForInstallationRecord(
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
): ServiceInstallOptions {
  if (
    options.controlSocket !== undefined &&
    options.controlSocket !== (record.controlSocket ?? undefined)
  ) {
    throw new Error(
      'The requested control channel does not match the service installation record.',
    );
  }
  const controlSocket = record.controlSocket ?? undefined;
  return {
    ...options,
    paths: controlSocket ? { ...options.paths, socketPath: controlSocket } : options.paths,
    controlSocket,
  };
}

async function quiesceInstalledService(options: ServiceInstallOptions): Promise<boolean> {
  return installedService(options).stopIfIdle();
}

async function waitForStartupServiceReady(options: ServiceInstallOptions): Promise<void> {
  if (options.waitForServiceReady) {
    await options.waitForServiceReady();
    return;
  }
  if (options.runner) {
    return;
  }
  const service = installedService(options);
  const deadline = Date.now() + 30_000;
  let lastError: unknown;
  while (Date.now() < deadline) {
    try {
      const status = await service.status();
      if (status.running && status.compatible) {
        return;
      }
    } catch (error) {
      lastError = error;
    }
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  throw new Error('Timed out waiting for the installed local TLS service to become ready.', {
    cause: lastError,
  });
}

async function writeRecord(
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
): Promise<void> {
  const finalPath = recordPath(options, record.version);
  const temporaryPath = `${finalPath}.${process.pid}.${randomUUID()}.tmp`;
  try {
    await writeFile(temporaryPath, `${JSON.stringify(record, null, 2)}\n`, { mode: 0o600 });
    await rename(temporaryPath, finalPath);
  } finally {
    await unlink(temporaryPath).catch(() => undefined);
  }
}

async function writePreviousRecord(
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
): Promise<void> {
  const finalPath = previousRecordPath(options);
  const temporaryPath = `${finalPath}.${process.pid}.${randomUUID()}.tmp`;
  try {
    await writeFile(temporaryPath, `${JSON.stringify(record, null, 2)}\n`, { mode: 0o600 });
    await rename(temporaryPath, finalPath);
  } finally {
    await unlink(temporaryPath).catch(() => undefined);
  }
}

async function assertOwnedDefinition(
  definitionPath: string,
  expectation?:
    | { options: ServiceInstallOptions; record: ServiceInstallationRecord }
    | Array<{ options: ServiceInstallOptions; record: ServiceInstallationRecord }>,
  requireExisting = false,
): Promise<void> {
  try {
    const details = await lstat(definitionPath);
    if (!details.isFile() || details.isSymbolicLink()) {
      throw new Error(`Refusing unsafe service definition: ${definitionPath}`);
    }
    const contents = await readFile(definitionPath, 'utf8');
    const expectations = Array.isArray(expectation)
      ? expectation
      : expectation
        ? [expectation]
        : [];
    if (
      expectations.length === 0 ||
      !expectations.some(({ options, record }) =>
        serviceDefinitionMatchesInstallation(contents, options, record),
      )
    ) {
      throw new Error(`Refusing to overwrite unrelated service definition: ${definitionPath}`);
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT' && requireExisting) {
      throw new Error(`The recorded startup service definition is missing: ${definitionPath}`);
    }
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
  }
}

function launchdDefinition(
  options: ServiceInstallOptions,
  identifier: string,
  recordVersion: 1 | 2 = 2,
): string {
  const user = os.userInfo();
  const username = options.username ?? user.username;
  const uid = options.uid ?? user.uid;
  const gid = options.gid ?? user.gid;
  const arguments_ = [
    options.nodePath,
    options.cliPath,
    'proxy',
    'start',
    '--service',
    '--namespace',
    options.namespace,
    '--run-as-uid',
    String(uid),
    '--run-as-gid',
    String(gid),
  ];
  if (options.controlSocket) {
    arguments_.push('--control-socket', options.controlSocket);
  }
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    '<dict>',
    `  <!-- ${recordVersion === 1 ? LEGACY_STARTUP_SERVICE_OWNER_MARKER : OWNER_MARKER} -->`,
    '  <key>Label</key>',
    `  <string>${xmlEscape(identifier)}</string>`,
    '  <key>ProgramArguments</key>',
    '  <array>',
    ...arguments_.map((argument) => `    <string>${xmlEscape(argument)}</string>`),
    '  </array>',
    '  <key>EnvironmentVariables</key>',
    '  <dict>',
    '    <key>HOME</key>',
    `    <string>${xmlEscape(options.homeDirectory ?? os.homedir())}</string>`,
    '    <key>USER</key>',
    `    <string>${xmlEscape(username)}</string>`,
    '    <key>LOGNAME</key>',
    `    <string>${xmlEscape(username)}</string>`,
    '    <key>VITE_LOCAL_TLS_USER_ID</key>',
    `    <string>${uid}</string>`,
    '    <key>VITE_LOCAL_TLS_RUNTIME_DIRECTORY</key>',
    `    <string>${xmlEscape(options.paths.runtimeDirectory)}</string>`,
    '  </dict>',
    '  <key>RunAtLoad</key>',
    '  <true/>',
    '  <key>KeepAlive</key>',
    ...(recordVersion === 1
      ? ['  <true/>']
      : ['  <dict>', '    <key>SuccessfulExit</key>', '    <false/>', '  </dict>']),
    '  <key>ProcessType</key>',
    '  <string>Background</string>',
    '  <key>StandardOutPath</key>',
    `  <string>${xmlEscape(path.join(options.paths.stateDirectory, 'service.log'))}</string>`,
    '  <key>StandardErrorPath</key>',
    `  <string>${xmlEscape(path.join(options.paths.stateDirectory, 'service-error.log'))}</string>`,
    '</dict>',
    '</plist>',
    '',
  ].join('\n');
}

async function installUserRuntime(
  options: ServiceInstallOptions,
  key: string,
): Promise<{ nodePath: string; cliPath: string; runtimeDirectory: string }> {
  const runtimeDirectory =
    options.runtimeInstallDirectory ??
    expectedRuntimeDirectory(
      options,
      options.platform ?? process.platform,
      safeServiceKey(options),
    );
  const nodePath = path.join(
    runtimeDirectory,
    (options.platform ?? process.platform) === 'win32' ? 'n.exe' : 'node',
  );
  const cliPath = path.join(
    runtimeDirectory,
    (options.platform ?? process.platform) === 'win32' ? 'c.js' : `cli-${key}.js`,
  );
  await mkdir(runtimeDirectory, { recursive: true, mode: 0o700 });
  await Promise.all([
    replaceRuntimeFile(options.nodePath, nodePath, options.platform ?? process.platform),
    replaceRuntimeFile(options.cliPath, cliPath, options.platform ?? process.platform),
  ]);
  return { nodePath, cliPath, runtimeDirectory };
}

async function replaceRuntimeFile(
  sourcePath: string,
  destinationPath: string,
  platform: NodeJS.Platform,
): Promise<void> {
  const temporaryPath = `${destinationPath}.${process.pid}.${randomUUID()}.tmp`;
  await copyFile(sourcePath, temporaryPath);
  try {
    if (platform !== 'win32') {
      await chmod(temporaryPath, 0o700);
      await rename(temporaryPath, destinationPath);
      return;
    }
    let lastError: unknown;
    for (let attempt = 0; attempt < 20; attempt += 1) {
      try {
        await copyFile(temporaryPath, destinationPath);
        return;
      } catch (error) {
        lastError = error;
        const code = (error as NodeJS.ErrnoException).code;
        if (!['EBUSY', 'EACCES', 'EPERM'].includes(code ?? '') || attempt === 19) {
          throw error;
        }
        await new Promise((resolve) => setTimeout(resolve, 50));
      }
    }
    throw lastError;
  } finally {
    await unlink(temporaryPath).catch(() => undefined);
  }
}

async function stageRegularFileBackup(sourcePath: string, backupPath: string): Promise<void> {
  const details = await lstat(sourcePath);
  if (!details.isFile() || details.isSymbolicLink()) {
    throw new Error(`Refusing unsafe installed service runtime: ${sourcePath}`);
  }
  try {
    const backupDetails = await lstat(backupPath);
    if (!backupDetails.isFile() || backupDetails.isSymbolicLink()) {
      throw new Error(`Refusing unsafe installed service backup: ${backupPath}`);
    }
    return;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
  }
  const temporaryPath = `${backupPath}.${process.pid}.${randomUUID()}.tmp`;
  try {
    await copyFile(sourcePath, temporaryPath);
    await rename(temporaryPath, backupPath);
  } finally {
    await unlink(temporaryPath).catch(() => undefined);
  }
}

function serviceBackupKey(
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
): string {
  const fingerprint = createHash('sha256')
    .update(JSON.stringify(record))
    .digest('hex')
    .slice(0, 12);
  return `${safeServiceKey(options)}-${fingerprint}`;
}

function systemdDefinition(options: ServiceInstallOptions, recordVersion: 1 | 2 = 2): string {
  const username = options.username ?? os.userInfo().username;
  const runtimeUnit = recordVersion === 2 ? linuxUserRuntimeUnit(options) : null;
  const arguments_ = [
    options.nodePath,
    options.cliPath,
    'proxy',
    'start',
    '--service',
    '--namespace',
    options.namespace,
  ];
  if (options.controlSocket) {
    arguments_.push('--control-socket', options.controlSocket);
  }
  return [
    `# ${recordVersion === 1 ? LEGACY_STARTUP_SERVICE_OWNER_MARKER : OWNER_MARKER}`,
    '[Unit]',
    'Description=Vite local TLS proxy',
    `After=network.target${runtimeUnit ? ` ${runtimeUnit}` : ''}`,
    ...(runtimeUnit ? [`Requires=${runtimeUnit}`] : []),
    '',
    '[Service]',
    'Type=simple',
    `User=${username}`,
    `Environment=HOME=${systemdQuote(options.homeDirectory ?? os.homedir())}`,
    `Environment=VITE_LOCAL_TLS_RUNTIME_DIRECTORY=${systemdQuote(options.paths.runtimeDirectory)}`,
    `ExecStart=${arguments_.map(systemdQuote).join(' ')}`,
    'Restart=on-failure',
    'RestartSec=1',
    'AmbientCapabilities=CAP_NET_BIND_SERVICE',
    'CapabilityBoundingSet=CAP_NET_BIND_SERVICE',
    'NoNewPrivileges=true',
    'PrivateTmp=false',
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    '',
  ].join('\n');
}

function usesSudo(options: ServiceInstallOptions): boolean {
  return options.useSudo === true || (options.useSudo !== false && process.getuid?.() !== 0);
}

function runElevatedCommand(
  options: ServiceInstallOptions,
  runner: ServiceInstallCommandRunner,
  command: string,
  arguments_: string[],
  timeoutMs?: number,
): Promise<ServiceInstallCommandResult> {
  const useSudo = usesSudo(options);
  if (!useSudo) {
    return timeoutMs ? runner(command, arguments_, { timeoutMs }) : runner(command, arguments_);
  }
  return runner('sudo', ['--', command, ...arguments_], {
    interactive: true,
    ...(timeoutMs ? { timeoutMs } : {}),
  });
}

async function runElevatedCommands(
  options: ServiceInstallOptions,
  runner: ServiceInstallCommandRunner,
  commands: ServiceInstallElevatedCommand[],
): Promise<void> {
  if ((options.platform ?? process.platform) === 'darwin' && usesSudo(options) && !process.env.CI) {
    await runner('/usr/bin/osascript', [
      '-e',
      'on run argv',
      '-e',
      'set commandPath to quoted form of (item 1 of argv)',
      '-e',
      'set source to quoted form of (item 2 of argv)',
      '-e',
      'set requests to quoted form of (item 3 of argv)',
      '-e',
      'do shell script (commandPath & " --input-type=module --eval " & source & " " & requests) with administrator privileges with prompt "Vite Local TLS needs permission to install or update its local HTTPS service."',
      '-e',
      'end run',
      process.execPath,
      MACOS_ELEVATED_SEQUENCE_SOURCE,
      JSON.stringify(commands),
    ]);
    return;
  }
  const rollback: ServiceInstallElevatedCommand[][] = [];
  for (const request of commands) {
    try {
      await runElevatedCommand(
        options,
        runner,
        request.command,
        request.arguments_,
        request.timeoutMs,
      );
      if (request.clearRollbackAfterSuccess) {
        rollback.length = 0;
      }
      if (request.discardRollbackAfterSuccess) {
        rollback.pop();
      }
      if (request.rollbackAfterSuccess?.length) {
        rollback.push(request.rollbackAfterSuccess);
      }
    } catch (error) {
      if (!request.allowFailure) {
        let rollbackFailed = false;
        for (const group of [...rollback].reverse()) {
          for (const recovery of group) {
            try {
              await runElevatedCommand(
                options,
                runner,
                recovery.command,
                recovery.arguments_,
                recovery.timeoutMs,
              );
            } catch {
              if (!recovery.allowFailure) {
                rollbackFailed = true;
                break;
              }
            }
          }
          if (rollbackFailed) {
            break;
          }
        }
        throw error;
      }
    }
  }
}

function macosBootoutCommands(
  installations: ObsoleteServiceInstallation[],
  clearRollbackAfterLast = false,
): ServiceInstallElevatedCommand[] {
  return installations.flatMap(({ record }, index) => [
    {
      command: 'launchctl',
      arguments_: ['bootout', `system/${record.identifier}`],
      allowFailure: true,
    },
    {
      command: process.execPath,
      arguments_: [
        '--input-type=module',
        '--eval',
        MACOS_LAUNCHD_REMOVAL_WAIT_SOURCE,
        record.identifier,
      ],
      clearRollbackAfterSuccess: clearRollbackAfterLast && index === installations.length - 1,
    },
  ]);
}

function macosCleanupCommands(
  installations: ObsoleteServiceInstallation[],
): ServiceInstallElevatedCommand[] {
  return installations.flatMap(({ installation, record }) => [
    {
      command: 'rm',
      arguments_: ['-f', record.definitionPath!],
      clearRollbackAfterSuccess: true,
    },
    {
      command: 'rm',
      arguments_: [
        '-f',
        recordPath(installation, 1),
        recordPath(installation, 2),
        previousRecordPath(installation),
      ],
    },
    ...(record.runtimeDirectory
      ? [{ command: 'rm', arguments_: ['-rf', record.runtimeDirectory] }]
      : []),
  ]);
}

function macosQuiesceCommands(
  installations: ObsoleteServiceInstallation[],
  restoreStoppedInstallations = false,
  controlClient?: MacosControlClient,
): ServiceInstallElevatedCommand[] {
  return installations.flatMap(({ installation, record, wasRunning }) => [
    {
      command: 'launchctl',
      arguments_: ['disable', `system/${record.identifier}`],
      rollbackAfterSuccess: [
        {
          command: 'launchctl',
          arguments_: ['enable', `system/${record.identifier}`],
        },
      ],
    },
    {
      command: controlClient?.nodePath ?? installation.nodePath,
      arguments_: [
        controlClient?.cliPath ?? installation.cliPath,
        'proxy',
        'stop',
        '--namespace',
        record.namespace,
        '--control-socket',
        installation.paths.socketPath,
      ],
      ...(wasRunning === false && !restoreStoppedInstallations
        ? { discardRollbackAfterSuccess: true }
        : {}),
      ...(wasRunning === false
        ? {}
        : {
            rollbackAfterSuccess: [
              {
                command: 'launchctl',
                arguments_: ['bootstrap', 'system', record.definitionPath!],
                allowFailure: true,
              },
              {
                command: 'launchctl',
                arguments_: ['enable', `system/${record.identifier}`],
              },
              {
                command: 'launchctl',
                arguments_: ['kickstart', `system/${record.identifier}`],
              },
            ],
          }),
    },
  ]);
}

async function stageMacosControlClient(
  options: ServiceInstallOptions,
): Promise<MacosControlClient> {
  const cliPath = path.join(
    options.paths.stateDirectory,
    `.service-control-${process.pid}-${randomUUID()}.js`,
  );
  await copyFile(options.readinessCliPath ?? options.cliPath, cliPath);
  await chmod(cliPath, 0o600);
  return { nodePath: process.execPath, cliPath };
}

async function inspectRunningInstallations(
  installations: ObsoleteServiceInstallation[],
): Promise<ObsoleteServiceInstallation[]> {
  return Promise.all(
    installations.map(async (item) => ({
      ...item,
      wasRunning: (await installedService(item.installation).status()).running,
    })),
  );
}

function macosReadinessCommand(
  nodePath: string,
  cliPath: string,
  namespace: string,
  controlSocket: string,
): ServiceInstallElevatedCommand {
  return {
    command: process.execPath,
    arguments_: [
      '--input-type=module',
      '--eval',
      MACOS_SERVICE_READINESS_WAIT_SOURCE,
      nodePath,
      cliPath,
      namespace,
      controlSocket,
    ],
    clearRollbackAfterSuccess: true,
    timeoutMs: 35_000,
  };
}

async function installMacos(
  options: ServiceInstallOptions,
  runner: ServiceInstallCommandRunner,
  identifier: string,
  plannedRecord: ServiceInstallationRecord,
  existingRecord: ServiceInstallationRecord | null,
  obsoleteInstallations: ObsoleteServiceInstallation[] = [],
): Promise<{
  definitionPath: string;
  nodePath: string;
  cliPath: string;
  runtimeDirectory: string;
}> {
  const definitionPath = path.join(
    options.definitionDirectory ?? '/Library/LaunchDaemons',
    `${identifier}.plist`,
  );
  const runtimeDirectory = expectedRuntimeDirectory(options, 'darwin', safeServiceKey(options));
  const nodePath = path.join(runtimeDirectory, 'node');
  const cliPath = path.join(runtimeDirectory, 'cli.js');
  const temporaryDefinitionPath = path.join(
    options.paths.stateDirectory,
    `${identifier}.plist.tmp`,
  );
  const temporaryCliPath = path.join(options.paths.stateDirectory, `${identifier}.cli.js.tmp`);
  const temporaryReadinessCliPath = path.join(
    options.paths.stateDirectory,
    `${identifier}.readiness-cli.tmp.js`,
  );
  const temporaryInstalledRecordPath = path.join(
    options.paths.stateDirectory,
    `${identifier}.service-install-v2.json.tmp`,
  );
  const backupKey = serviceBackupKey(options, existingRecord ?? plannedRecord);
  const previousDefinitionPath = path.join(
    options.paths.stateDirectory,
    `${backupKey}.previous.plist.tmp`,
  );
  const previousNodePath = path.join(
    options.paths.stateDirectory,
    `${backupKey}.previous.node.tmp`,
  );
  const previousCliPath = path.join(
    options.paths.stateDirectory,
    `${backupKey}.previous.cli.js.tmp`,
  );
  await assertOwnedDefinition(
    definitionPath,
    existingRecord
      ? [
          {
            options: optionsForInstallationRecord(options, existingRecord),
            record: existingRecord,
          },
          { options, record: plannedRecord },
        ]
      : { options, record: plannedRecord },
  );
  for (const { installation, record } of obsoleteInstallations) {
    await assertOwnedDefinition(record.definitionPath!, { options: installation, record }, true);
  }
  try {
    const trackedExisting = existingRecord
      ? (
          await inspectRunningInstallations([
            {
              installation: optionsForInstallationRecord(options, existingRecord),
              record: existingRecord,
            },
          ])
        )[0]!
      : null;
    const trackedObsolete = await inspectRunningInstallations(obsoleteInstallations);
    const rollbackWinnerIdentifier =
      (trackedExisting?.wasRunning ? trackedExisting.record.identifier : null) ??
      trackedObsolete.find(({ wasRunning }) => wasRunning)?.record.identifier ??
      null;
    const rollbackExisting = trackedExisting
      ? {
          ...trackedExisting,
          wasRunning: trackedExisting.record.identifier === rollbackWinnerIdentifier,
        }
      : null;
    const rollbackObsolete = trackedObsolete.map((installation) => ({
      ...installation,
      wasRunning: installation.record.identifier === rollbackWinnerIdentifier,
    }));
    if (!existingRecord) {
      await quiesceInstalledService(options);
    } else {
      await Promise.all([
        stageRegularFileBackup(definitionPath, previousDefinitionPath),
        stageRegularFileBackup(existingRecord.nodePath, previousNodePath),
        stageRegularFileBackup(existingRecord.cliPath, previousCliPath),
      ]);
    }
    await writeFile(
      temporaryDefinitionPath,
      launchdDefinition({ ...options, nodePath, cliPath }, identifier),
      { mode: 0o600 },
    );
    if (plannedRecord.version !== 2) {
      throw new Error('The planned canonical service record must use version 2.');
    }
    await writeFile(
      temporaryInstalledRecordPath,
      `${JSON.stringify({ ...plannedRecord, installationState: 'installed' }, null, 2)}\n`,
      { mode: 0o600 },
    );
    await copyFile(options.cliPath, temporaryCliPath);
    await copyFile(options.readinessCliPath ?? options.cliPath, temporaryReadinessCliPath);
    await runElevatedCommands(options, runner, [
      ...(existingRecord
        ? macosQuiesceCommands([rollbackExisting!], rollbackWinnerIdentifier === null, {
            nodePath: process.execPath,
            cliPath: temporaryReadinessCliPath,
          })
        : []),
      ...macosQuiesceCommands(rollbackObsolete, false, {
        nodePath: process.execPath,
        cliPath: temporaryReadinessCliPath,
      }),
      ...(existingRecord
        ? [
            {
              command: 'test',
              arguments_: ['-f', previousDefinitionPath],
              rollbackAfterSuccess: [
                {
                  command: 'launchctl',
                  arguments_: ['bootout', `system/${identifier}`],
                  allowFailure: true,
                },
                {
                  command: process.execPath,
                  arguments_: [
                    '--input-type=module',
                    '--eval',
                    MACOS_LAUNCHD_REMOVAL_WAIT_SOURCE,
                    identifier,
                  ],
                },
                {
                  command: 'install',
                  arguments_: ['-m', '0755', previousNodePath, nodePath],
                },
                {
                  command: 'install',
                  arguments_: ['-m', '0644', previousCliPath, cliPath],
                },
                {
                  command: 'install',
                  arguments_: ['-m', '0644', previousDefinitionPath, definitionPath],
                },
              ],
            },
          ]
        : []),
      ...macosBootoutCommands(trackedObsolete),
      { command: 'mkdir', arguments_: ['-p', runtimeDirectory] },
      { command: 'install', arguments_: ['-m', '0755', options.nodePath, nodePath] },
      { command: 'install', arguments_: ['-m', '0644', temporaryCliPath, cliPath] },
      {
        command: 'install',
        arguments_: ['-m', '0644', temporaryDefinitionPath, definitionPath],
      },
      {
        command: 'launchctl',
        arguments_: ['bootout', `system/${identifier}`],
        allowFailure: true,
      },
      {
        command: process.execPath,
        arguments_: [
          '--input-type=module',
          '--eval',
          MACOS_LAUNCHD_REMOVAL_WAIT_SOURCE,
          identifier,
        ],
      },
      {
        command: 'launchctl',
        arguments_: ['bootstrap', 'system', definitionPath],
        ...(!existingRecord
          ? {
              rollbackAfterSuccess: [
                {
                  command: 'launchctl',
                  arguments_: ['bootout', `system/${identifier}`],
                  allowFailure: true,
                },
                {
                  command: process.execPath,
                  arguments_: [
                    '--input-type=module',
                    '--eval',
                    MACOS_LAUNCHD_REMOVAL_WAIT_SOURCE,
                    identifier,
                  ],
                },
                { command: 'rm', arguments_: ['-f', definitionPath] },
                { command: 'rm', arguments_: ['-rf', runtimeDirectory] },
              ],
            }
          : {}),
      },
      { command: 'launchctl', arguments_: ['enable', `system/${identifier}`] },
      {
        command: 'launchctl',
        arguments_: ['kickstart', '-k', `system/${identifier}`],
      },
      macosReadinessCommand(
        process.execPath,
        temporaryReadinessCliPath,
        options.namespace,
        options.paths.socketPath,
      ),
      {
        command: 'mv',
        arguments_: ['-f', temporaryInstalledRecordPath, recordPath(options, 2)],
      },
      ...macosCleanupCommands(trackedObsolete),
    ]);
  } finally {
    await Promise.all([
      unlink(temporaryDefinitionPath).catch(() => undefined),
      unlink(temporaryCliPath).catch(() => undefined),
      unlink(temporaryReadinessCliPath).catch(() => undefined),
      unlink(temporaryInstalledRecordPath).catch(() => undefined),
      unlink(previousDefinitionPath).catch(() => undefined),
      unlink(previousNodePath).catch(() => undefined),
      unlink(previousCliPath).catch(() => undefined),
    ]);
  }
  return { definitionPath, nodePath, cliPath, runtimeDirectory };
}

async function installLinux(
  options: ServiceInstallOptions,
  runner: ServiceInstallCommandRunner,
  identifier: string,
  plannedRecord: ServiceInstallationRecord,
  existingRecord: ServiceInstallationRecord | null,
  obsoleteInstallations: ObsoleteServiceInstallation[] = [],
): Promise<{
  definitionPath: string;
  nodePath: string;
  cliPath: string;
  runtimeDirectory: string;
}> {
  const definitionPath = path.join(
    options.definitionDirectory ?? '/etc/systemd/system',
    `${identifier}.service`,
  );
  await assertOwnedDefinition(
    definitionPath,
    existingRecord
      ? [
          {
            options: optionsForInstallationRecord(options, existingRecord),
            record: existingRecord,
          },
          { options, record: plannedRecord },
        ]
      : { options, record: plannedRecord },
  );
  for (const { installation, record } of obsoleteInstallations) {
    await assertOwnedDefinition(record.definitionPath!, { options: installation, record }, true);
  }
  const temporaryPath = path.join(options.paths.stateDirectory, `${identifier}.service.tmp`);
  const backupKey = serviceBackupKey(options, existingRecord ?? plannedRecord);
  const previousDefinitionPath = path.join(
    options.paths.stateDirectory,
    `${backupKey}.previous.service.tmp`,
  );
  const previousNodePath = path.join(
    options.paths.stateDirectory,
    `${backupKey}.previous.node.tmp`,
  );
  const previousCliPath = path.join(
    options.paths.stateDirectory,
    `${backupKey}.previous.cli.js.tmp`,
  );
  async function runElevated(
    command: string,
    arguments_: string[],
  ): Promise<ServiceInstallCommandResult> {
    return runElevatedCommand(options, runner, command, arguments_);
  }
  const disabledInstallations: ObsoleteServiceInstallation[] = [];
  const stoppedIdentifiers = new Set<string>();
  let runtime: Awaited<ReturnType<typeof installUserRuntime>> | null = null;
  let canonicalMutationStarted = false;
  let canonicalStarted = false;
  try {
    if (existingRecord) {
      await Promise.all([
        stageRegularFileBackup(definitionPath, previousDefinitionPath),
        stageRegularFileBackup(existingRecord.nodePath, previousNodePath),
        stageRegularFileBackup(existingRecord.cliPath, previousCliPath),
      ]);
    }
    const canonicalOptions = existingRecord
      ? optionsForInstallationRecord(options, existingRecord)
      : options;
    if (await quiesceInstalledService(canonicalOptions)) {
      if (existingRecord) {
        stoppedIdentifiers.add(existingRecord.identifier);
      }
    }
    for (const { installation, record } of obsoleteInstallations) {
      if (await quiesceInstalledService(installation)) {
        stoppedIdentifiers.add(record.identifier);
      }
    }
    for (const installation of obsoleteInstallations) {
      disabledInstallations.push(installation);
      const { record } = installation;
      await runElevated('systemctl', ['disable', '--now', `${record.identifier}.service`]);
    }
    canonicalMutationStarted = true;
    runtime = await installUserRuntime(options, safeServiceKey(options));
    const serviceOptions = { ...options, nodePath: runtime.nodePath, cliPath: runtime.cliPath };
    await writeFile(temporaryPath, systemdDefinition(serviceOptions), { mode: 0o600 });
    await runElevated('install', ['-m', '0644', '--', temporaryPath, definitionPath]);
    await runElevated('systemctl', ['daemon-reload']);
    await runElevated('systemctl', ['enable', '--now', `${identifier}.service`]);
    await waitForStartupServiceReady({
      ...options,
      nodePath: runtime.nodePath,
      cliPath: runtime.cliPath,
    });
    if (plannedRecord.version !== 2) {
      throw new Error('The planned canonical service record must use version 2.');
    }
    await writeRecord(options, { ...plannedRecord, installationState: 'installed' });
    canonicalStarted = true;
    for (const { record } of obsoleteInstallations) {
      await runElevated('rm', ['-f', '--', record.definitionPath!]);
    }
    if (obsoleteInstallations.length > 0) {
      await runElevated('systemctl', ['daemon-reload']);
    }
    await Promise.all(
      obsoleteInstallations.map(({ installation }) => removeInstallationRecords(installation)),
    );
    await Promise.all(
      obsoleteInstallations.flatMap(({ record }) =>
        record.runtimeDirectory
          ? [rm(record.runtimeDirectory, { recursive: true, force: true })]
          : [],
      ),
    );
  } catch (error) {
    if (!canonicalStarted) {
      if (canonicalMutationStarted) {
        await runElevated('systemctl', ['disable', '--now', `${identifier}.service`]).catch(
          () => undefined,
        );
      }
      if (existingRecord && canonicalMutationStarted) {
        try {
          await Promise.all([
            replaceRuntimeFile(previousNodePath, existingRecord.nodePath, 'linux'),
            replaceRuntimeFile(previousCliPath, existingRecord.cliPath, 'linux'),
          ]);
          await runElevated('install', [
            '-m',
            '0644',
            '--',
            previousDefinitionPath,
            definitionPath,
          ]);
          await runElevated('systemctl', ['daemon-reload']);
        } catch (rollbackError) {
          throw new AggregateError(
            [error, rollbackError],
            'The canonical systemd update failed and its previous runtime could not be restored safely.',
          );
        }
      }
      const restoredIdentifiers = new Set<string>();
      const restoreCanonical = Boolean(
        existingRecord && stoppedIdentifiers.has(existingRecord.identifier),
      );
      if (!restoreCanonical) {
        for (const { record } of [...disabledInstallations].reverse()) {
          if (!stoppedIdentifiers.has(record.identifier)) {
            continue;
          }
          try {
            await runElevated('systemctl', ['enable', '--now', `${record.identifier}.service`]);
            restoredIdentifiers.add(record.identifier);
            break;
          } catch {
            await runElevated('systemctl', [
              'disable',
              '--now',
              `${record.identifier}.service`,
            ]).catch(() => undefined);
          }
        }
        for (const { record } of [...obsoleteInstallations].reverse()) {
          if (
            restoredIdentifiers.size > 0 ||
            !stoppedIdentifiers.has(record.identifier) ||
            disabledInstallations.some(
              ({ record: disabledRecord }) => disabledRecord.identifier === record.identifier,
            )
          ) {
            continue;
          }
          try {
            await runElevated('systemctl', ['start', `${record.identifier}.service`]);
            restoredIdentifiers.add(record.identifier);
          } catch {
            await runElevated('systemctl', [
              'disable',
              '--now',
              `${record.identifier}.service`,
            ]).catch(() => undefined);
          }
        }
      }
      if (existingRecord) {
        if (restoredIdentifiers.size > 0) {
          await runElevated('systemctl', [
            'disable',
            '--now',
            `${existingRecord.identifier}.service`,
          ]).catch(() => undefined);
        } else if (canonicalMutationStarted) {
          await runElevated('systemctl', [
            'enable',
            ...(restoreCanonical ? ['--now'] : []),
            `${existingRecord.identifier}.service`,
          ]).catch(() => undefined);
        } else if (restoreCanonical) {
          await runElevated('systemctl', ['start', `${existingRecord.identifier}.service`]).catch(
            () => undefined,
          );
        }
      }
    }
    throw error;
  } finally {
    await Promise.all([
      unlink(temporaryPath).catch(() => undefined),
      unlink(previousDefinitionPath).catch(() => undefined),
      unlink(previousNodePath).catch(() => undefined),
      unlink(previousCliPath).catch(() => undefined),
    ]);
  }
  return {
    definitionPath,
    nodePath: runtime!.nodePath,
    cliPath: runtime!.cliPath,
    runtimeDirectory: runtime!.runtimeDirectory,
  };
}

async function windowsTaskExists(
  runner: ServiceInstallCommandRunner,
  identifier: string,
): Promise<boolean> {
  return runner('schtasks.exe', ['/Query', '/TN', identifier])
    .then(() => true)
    .catch(() => false);
}

async function installWindows(
  options: ServiceInstallOptions,
  runner: ServiceInstallCommandRunner,
  identifier: string,
  plannedRecord: ServiceInstallationRecord,
  existingRecord: ServiceInstallationRecord | null,
): Promise<{ nodePath: string; cliPath: string; runtimeDirectory: string }> {
  const taskExists = await windowsTaskExists(runner, identifier);
  if (taskExists) {
    if (!existingRecord) {
      await assertOwnedWindowsStartupTask(runner, plannedRecord).catch(() => {
        throw new Error(`Refusing to replace unrelated scheduled task: ${identifier}`);
      });
    } else {
      await assertOwnedWindowsStartupTask(runner, existingRecord).catch(async () => {
        await assertOwnedWindowsStartupTask(runner, plannedRecord);
      });
    }
  }
  const plannedRuntimeDirectory = expectedRuntimeDirectory(
    options,
    'win32',
    safeServiceKey(options),
  );
  const backupKey = serviceBackupKey(options, existingRecord ?? plannedRecord);
  const previousNodePath = path.join(
    options.paths.stateDirectory,
    `${backupKey}.previous.node.tmp`,
  );
  const previousCliPath = path.join(options.paths.stateDirectory, `${backupKey}.previous.cli.tmp`);
  const previousConfigurationPath = path.join(
    options.paths.stateDirectory,
    `${backupKey}.previous.config.tmp`,
  );
  let runtime: Awaited<ReturnType<typeof installUserRuntime>> | null = null;
  let runtimeMutationStarted = false;
  let taskCreated = false;
  let wasRunning = false;
  try {
    if (existingRecord) {
      await Promise.all([
        stageRegularFileBackup(existingRecord.nodePath, previousNodePath),
        stageRegularFileBackup(existingRecord.cliPath, previousCliPath),
        stageRegularFileBackup(
          windowsConfigurationPath(existingRecord.runtimeDirectory!),
          previousConfigurationPath,
        ),
      ]);
    }
    wasRunning = await quiesceInstalledService(
      existingRecord ? optionsForInstallationRecord(options, existingRecord) : options,
    );
    if (taskExists) {
      await runner('schtasks.exe', ['/End', '/TN', identifier]).catch(() => undefined);
    }
    runtimeMutationStarted = true;
    runtime = await installUserRuntime(options, safeServiceKey(options));
    const configurationPath = windowsConfigurationPath(runtime.runtimeDirectory);
    const configuration: ServiceRuntimeConfiguration = {
      version: 1,
      owner: '@vampaz/vite-plugin-local-tls',
      namespace: options.namespace,
      controlSocket: options.controlSocket ?? null,
    };
    await writeFile(configurationPath, `${JSON.stringify(configuration, null, 2)}\n`, {
      mode: 0o600,
    });
    const command = windowsTaskCommand(runtime.nodePath, runtime.cliPath, configurationPath);
    if (command.length > 261) {
      throw new Error('Windows Task Scheduler command exceeds its 261-character limit.');
    }
    await runner('schtasks.exe', [
      '/Create',
      '/TN',
      identifier,
      '/TR',
      command,
      '/SC',
      'ONLOGON',
      '/RL',
      'LIMITED',
      ...(taskExists ? ['/F'] : []),
    ]);
    taskCreated = true;
    await runner('schtasks.exe', ['/Run', '/TN', identifier]);
    await waitForStartupServiceReady({
      ...options,
      nodePath: runtime.nodePath,
      cliPath: runtime.cliPath,
    });
    return runtime;
  } catch (error) {
    if (existingRecord && runtimeMutationStarted) {
      try {
        await Promise.all([
          replaceRuntimeFile(previousNodePath, existingRecord.nodePath, 'win32'),
          replaceRuntimeFile(previousCliPath, existingRecord.cliPath, 'win32'),
          replaceRuntimeFile(
            previousConfigurationPath,
            windowsConfigurationPath(existingRecord.runtimeDirectory!),
            'win32',
          ),
        ]);
        if (taskExists) {
          const previousCommand = windowsTaskCommand(
            existingRecord.nodePath,
            existingRecord.cliPath,
            windowsConfigurationPath(existingRecord.runtimeDirectory!),
          );
          await runner('schtasks.exe', [
            '/Create',
            '/TN',
            identifier,
            '/TR',
            previousCommand,
            '/SC',
            'ONLOGON',
            '/RL',
            'LIMITED',
            '/F',
          ]);
          if (wasRunning) {
            await runner('schtasks.exe', ['/Run', '/TN', identifier]);
          }
        }
      } catch (rollbackError) {
        throw new AggregateError(
          [error, rollbackError],
          'The canonical scheduled-task update failed and its previous runtime could not be restored safely.',
        );
      }
    }
    throw error;
  } finally {
    await Promise.all([
      unlink(previousNodePath).catch(() => undefined),
      unlink(previousCliPath).catch(() => undefined),
      unlink(previousConfigurationPath).catch(() => undefined),
    ]);
    if (!existingRecord && !taskExists && !taskCreated) {
      await rm(plannedRuntimeDirectory, { recursive: true, force: true }).catch(() => undefined);
    }
  }
}

export async function assertOwnedWindowsStartupTask(
  runner: ServiceInstallCommandRunner,
  record: ServiceInstallationRecord,
): Promise<void> {
  const task = await runner('schtasks.exe', ['/Query', '/TN', record.identifier, '/XML']);
  const configurationPath = windowsConfigurationPath(record.runtimeDirectory!);
  const configurationDetails = await lstat(configurationPath);
  if (!configurationDetails.isFile() || configurationDetails.isSymbolicLink()) {
    throw new Error(`Refusing unsafe scheduled task configuration: ${configurationPath}`);
  }
  const configuration = JSON.parse(
    await readFile(configurationPath, 'utf8'),
  ) as ServiceRuntimeConfiguration;
  const ownsConfiguration =
    configuration.version === 1 &&
    configuration.owner === '@vampaz/vite-plugin-local-tls' &&
    configuration.namespace === record.namespace &&
    configuration.controlSocket === record.controlSocket;
  const taskPaths = windowsTaskPathCandidates(record.nodePath);
  const taskArguments = windowsTaskArgumentCandidates(record.cliPath, configurationPath);
  const taskXml = xmlWithoutComments(task.stdout);
  const actions = singleXmlContainer(taskXml, 'Actions');
  const action = actions ? singleXmlContainer(actions, 'Exec') : null;
  const expectedActions = taskPaths.flatMap((taskPath) =>
    taskArguments.map((arguments_) =>
      [
        '<Command>',
        xmlEscape(taskPath),
        '</Command>',
        '<Arguments>',
        xmlEscape(arguments_),
        '</Arguments>',
      ].join(''),
    ),
  );
  const normalizedActions = expectedActions.map((expectedAction) =>
    normalizeXmlDefinition(expectedAction),
  );
  const ownsTask =
    ownsConfiguration &&
    actions !== null &&
    action !== null &&
    normalizedActions.some(
      (expectedAction) => normalizeXmlDefinition(actions) === `<Exec>${expectedAction}</Exec>`,
    ) &&
    normalizedActions.includes(normalizeXmlDefinition(action)) &&
    taskPaths.includes(singleXmlElement(taskXml, 'Command') ?? '') &&
    taskArguments.includes(singleXmlElement(taskXml, 'Arguments') ?? '');
  if (!ownsTask) {
    throw new Error(`Refusing to operate on unrelated scheduled task: ${record.identifier}`);
  }
}

async function hasOwnedPersistentTarget(
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
  runner: ServiceInstallCommandRunner,
): Promise<boolean> {
  const platform = options.platform ?? process.platform;
  if (platform === 'win32') {
    if (!(await windowsTaskExists(runner, record.identifier))) {
      return false;
    }
    try {
      await assertOwnedWindowsStartupTask(runner, record);
      return true;
    } catch {
      return false;
    }
  }
  try {
    await assertOwnedDefinition(record.definitionPath!, { options, record }, true);
    return true;
  } catch {
    return false;
  }
}

async function installStartupServiceRecords(
  options: ServiceInstallOptions,
  obsoleteInstallations: ObsoleteServiceInstallation[],
): Promise<ServiceInstallResult> {
  await ensureStatePaths(options.paths);
  const platform = options.platform ?? process.platform;
  const key = safeServiceKey(options);
  const runner = options.runner ?? executeCommand;
  const identifier = serviceIdentifier(platform, key);
  const existingRecord = await readRecord(options);
  const previousRecord =
    existingRecord?.version === 2 && existingRecord.installationState === 'installing'
      ? await readPreviousRecord(options)
      : existingRecord;
  if (existingRecord && existingRecord === previousRecord) {
    await writePreviousRecord(options, existingRecord);
  }
  if (previousRecord?.version === 1) {
    await unlink(recordPath(options, 1)).catch((error: NodeJS.ErrnoException) => {
      if (error.code !== 'ENOENT') {
        throw error;
      }
    });
  }
  const plannedRuntimeDirectory = expectedRuntimeDirectory(options, platform, key);
  const plannedRecord: ServiceInstallationRecord = {
    version: 2,
    packageVersion: options.currentVersion ?? PACKAGE_VERSION,
    protocolVersion: CONTROL_PROTOCOL_VERSION,
    installationState: 'installing',
    platform,
    namespace: options.namespace,
    identifier,
    definitionPath: expectedDefinitionPath(options, platform, identifier),
    nodePath: path.join(plannedRuntimeDirectory, platform === 'win32' ? 'n.exe' : 'node'),
    cliPath: path.join(
      plannedRuntimeDirectory,
      platform === 'darwin' ? 'cli.js' : platform === 'win32' ? 'c.js' : `cli-${key}.js`,
    ),
    runtimeDirectory: plannedRuntimeDirectory,
    controlSocket: options.controlSocket ?? null,
    installedAt: new Date().toISOString(),
  };
  if (previousRecord) {
    await writeRecord(options, plannedRecord);
  } else {
    await unlink(recordPath(options, 2)).catch((error: NodeJS.ErrnoException) => {
      if (error.code !== 'ENOENT') {
        throw error;
      }
    });
  }
  let definitionPath: string | null = null;
  let installedNodePath = options.nodePath;
  let installedCliPath = options.cliPath;
  let runtimeDirectory: string | undefined;
  try {
    if (platform === 'darwin') {
      const installed = await installMacos(
        options,
        runner,
        identifier,
        plannedRecord,
        previousRecord,
        obsoleteInstallations,
      );
      definitionPath = installed.definitionPath;
      installedNodePath = installed.nodePath;
      installedCliPath = installed.cliPath;
      runtimeDirectory = installed.runtimeDirectory;
    } else if (platform === 'linux') {
      const installed = await installLinux(
        options,
        runner,
        identifier,
        plannedRecord,
        previousRecord,
        obsoleteInstallations,
      );
      definitionPath = installed.definitionPath;
      installedNodePath = installed.nodePath;
      installedCliPath = installed.cliPath;
      runtimeDirectory = installed.runtimeDirectory;
    } else if (platform === 'win32') {
      const installed = await installWindows(
        options,
        runner,
        identifier,
        plannedRecord,
        previousRecord,
      );
      installedNodePath = installed.nodePath;
      installedCliPath = installed.cliPath;
      runtimeDirectory = installed.runtimeDirectory;
    } else {
      throw new Error(`Unsupported service platform: ${platform}`);
    }
  } catch (error) {
    const currentRecord = await readRecord(options).catch(() => null);
    const committed =
      currentRecord?.version === 2 &&
      plannedRecord.version === 2 &&
      currentRecord.installationState === 'installed' &&
      currentRecord.packageVersion === plannedRecord.packageVersion &&
      currentRecord.protocolVersion === plannedRecord.protocolVersion &&
      currentRecord.installedAt === plannedRecord.installedAt &&
      (await hasOwnedPersistentTarget(options, currentRecord, runner));
    if (committed) {
      throw error;
    }
    if (previousRecord) {
      if (await hasOwnedPersistentTarget(options, previousRecord, runner)) {
        await writeRecord(options, previousRecord);
        if (previousRecord.version === 1) {
          await unlink(recordPath(options, 2)).catch(() => undefined);
        }
        await unlink(previousRecordPath(options)).catch(() => undefined);
      }
    } else if (await hasOwnedPersistentTarget(options, plannedRecord, runner)) {
      await writeRecord(options, plannedRecord);
    } else {
      await unlink(recordPath(options, 2)).catch(() => undefined);
    }
    throw error;
  }
  const record: ServiceInstallationRecord = {
    version: 2,
    packageVersion: options.currentVersion ?? PACKAGE_VERSION,
    protocolVersion: CONTROL_PROTOCOL_VERSION,
    installationState: 'installed',
    platform,
    namespace: options.namespace,
    identifier,
    definitionPath,
    nodePath: installedNodePath,
    cliPath: installedCliPath,
    runtimeDirectory,
    controlSocket: options.controlSocket ?? null,
    installedAt: new Date().toISOString(),
  };
  await writeRecord(options, record);
  await unlink(recordPath(options, 1)).catch((error: NodeJS.ErrnoException) => {
    if (error.code !== 'ENOENT') {
      throw error;
    }
  });
  await unlink(previousRecordPath(options)).catch((error: NodeJS.ErrnoException) => {
    if (error.code !== 'ENOENT') {
      throw error;
    }
  });
  return { installed: true, record };
}

function assertCanonicalInstallation(options: ServiceInstallOptions): void {
  if (options.namespace !== CANONICAL_SERVICE_NAMESPACE) {
    throw new Error(
      'Port 443 has one machine-wide startup service. Install the canonical `default` service instead of a namespaced startup service.',
    );
  }
  if (options.controlSocket !== undefined) {
    throw new Error(
      'The canonical startup service has one control channel. Omit `controlSocket` when installing it.',
    );
  }
}

function newerIncompatibleError(): Error {
  return new Error(
    'A newer installed local TLS service uses an incompatible control protocol. Update this project to the newer plugin version; the installed runtime was left unchanged.',
  );
}

export async function installStartupService(
  options: ServiceInstallOptions,
): Promise<ServiceInstallResult> {
  assertCanonicalInstallation(options);
  const updateStatus = await getStartupServiceUpdateStatus(options);
  if (updateStatus === 'newer') {
    return startStartupService(options);
  }
  if (updateStatus === 'newer-incompatible') {
    throw newerIncompatibleError();
  }
  return installStartupServiceRecords(options, []);
}

export async function replaceStartupService(
  options: ServiceInstallOptions,
  obsoleteInstallations: ServiceInstallOptions[],
): Promise<ServiceInstallResult> {
  assertCanonicalInstallation(options);
  const updateStatus = await getStartupServiceUpdateStatus(options);
  if (updateStatus === 'newer') {
    return startStartupService(options, obsoleteInstallations);
  }
  if (updateStatus === 'newer-incompatible') {
    throw newerIncompatibleError();
  }
  const platform = options.platform ?? process.platform;
  const obsolete = await Promise.all(
    obsoleteInstallations.map(async (installation) => {
      const record = await readRecord(installation);
      if (!record) {
        return null;
      }
      if (record.platform !== platform || record.namespace === CANONICAL_SERVICE_NAMESPACE) {
        throw new Error('Refusing to replace a startup service outside the legacy target set.');
      }
      return { installation: optionsForInstallationRecord(installation, record), record };
    }),
  );
  const existing = obsolete.filter(
    (item): item is { installation: ServiceInstallOptions; record: ServiceInstallationRecord } =>
      item !== null,
  );
  if (platform === 'win32') {
    const runner = options.runner ?? executeCommand;
    const initialCanonicalRecord = await readRecord(options);
    const initialCanonicalWasRunning = initialCanonicalRecord
      ? (
          await installedService(
            optionsForInstallationRecord(options, initialCanonicalRecord),
          ).status()
        ).running
      : false;
    if (await windowsTaskExists(runner, serviceIdentifier(platform, safeServiceKey(options)))) {
      if (!initialCanonicalRecord) {
        throw new Error('Refusing to replace an unrelated canonical scheduled task.');
      }
      await assertOwnedWindowsStartupTask(runner, initialCanonicalRecord);
    }
    for (const { record } of existing) {
      await assertOwnedWindowsStartupTask(runner, record);
    }
    const disabled: ObsoleteServiceInstallation[] = [];
    const stoppedIdentifiers = new Set<string>();
    let canonicalInstallAttempted = false;
    let result: ServiceInstallResult;
    try {
      for (const item of existing) {
        if (await quiesceInstalledService(item.installation)) {
          stoppedIdentifiers.add(item.record.identifier);
        }
      }
      for (const item of existing) {
        disabled.push(item);
        await runner('schtasks.exe', ['/Change', '/TN', item.record.identifier, '/Disable']);
      }
      canonicalInstallAttempted = true;
      result = await installStartupServiceRecords(options, []);
    } catch (error) {
      let canonicalRecord = canonicalInstallAttempted
        ? await readRecord(options).catch(() => null)
        : null;
      let canonicalOwned = canonicalRecord
        ? await hasOwnedPersistentTarget(options, canonicalRecord, runner)
        : false;
      const previousCanonicalOwned = initialCanonicalRecord
        ? await hasOwnedPersistentTarget(options, initialCanonicalRecord, runner)
        : false;
      if (canonicalOwned && !previousCanonicalOwned) {
        await uninstallStartupService(options).catch(() => undefined);
        canonicalRecord = await readRecord(options).catch(() => null);
        canonicalOwned = canonicalRecord
          ? await hasOwnedPersistentTarget(options, canonicalRecord, runner)
          : false;
      }
      const canonicalTargetPresent = await windowsTaskExists(
        runner,
        serviceIdentifier(platform, safeServiceKey(options)),
      );
      let canonicalDisabledForLegacy = !canonicalTargetPresent;
      if (
        canonicalTargetPresent &&
        previousCanonicalOwned &&
        !initialCanonicalWasRunning &&
        stoppedIdentifiers.size > 0
      ) {
        await runner('schtasks.exe', [
          '/End',
          '/TN',
          serviceIdentifier(platform, safeServiceKey(options)),
        ]).catch(() => undefined);
        canonicalDisabledForLegacy = await runner('schtasks.exe', [
          '/Change',
          '/TN',
          serviceIdentifier(platform, safeServiceKey(options)),
          '/Disable',
        ])
          .then(() => true)
          .catch(() => false);
      }
      if (
        stoppedIdentifiers.size > 0 &&
        ((!canonicalOwned && !canonicalTargetPresent) || canonicalDisabledForLegacy)
      ) {
        const restoredIdentifiers = new Set<string>();
        for (const item of [...disabled].reverse()) {
          if (restoredIdentifiers.size > 0 || !stoppedIdentifiers.has(item.record.identifier)) {
            continue;
          }
          try {
            await runner('schtasks.exe', ['/Change', '/TN', item.record.identifier, '/Enable']);
            await runner('schtasks.exe', ['/Run', '/TN', item.record.identifier]);
            restoredIdentifiers.add(item.record.identifier);
          } catch {
            await runner('schtasks.exe', [
              '/Change',
              '/TN',
              item.record.identifier,
              '/Disable',
            ]).catch(() => undefined);
            continue;
          }
        }
        for (const item of [...existing].reverse()) {
          if (
            restoredIdentifiers.size > 0 ||
            !stoppedIdentifiers.has(item.record.identifier) ||
            disabled.some(
              ({ record: disabledRecord }) => disabledRecord.identifier === item.record.identifier,
            )
          ) {
            continue;
          }
          try {
            await runner('schtasks.exe', ['/Run', '/TN', item.record.identifier]);
            restoredIdentifiers.add(item.record.identifier);
            break;
          } catch {
            await runner('schtasks.exe', [
              '/Change',
              '/TN',
              item.record.identifier,
              '/Disable',
            ]).catch(() => undefined);
          }
        }
      }
      throw error;
    }
    for (const { installation } of existing) {
      await uninstallStartupService(installation);
    }
    return result;
  }
  const result = await installStartupServiceRecords(options, existing);
  await Promise.all(existing.map(({ installation }) => removeInstallationRecords(installation)));
  return result;
}

export async function startStartupService(
  options: ServiceInstallOptions,
  obsoleteInstallations: ServiceInstallOptions[] = [],
): Promise<ServiceInstallResult> {
  assertCanonicalInstallation(options);
  if ((await getStartupServiceUpdateStatus(options)) === 'newer-incompatible') {
    throw newerIncompatibleError();
  }
  const record = await readRecord(options);
  if (!record) {
    throw new Error('The canonical startup service is not installed.');
  }
  const canonicalOptions = optionsForInstallationRecord(options, record);
  const platform = options.platform ?? process.platform;
  const obsolete = await Promise.all(
    obsoleteInstallations.map(async (installation) => {
      const obsoleteRecord = await readRecord(installation);
      if (!obsoleteRecord) {
        return null;
      }
      if (
        obsoleteRecord.platform !== platform ||
        obsoleteRecord.namespace === CANONICAL_SERVICE_NAMESPACE
      ) {
        throw new Error('Refusing to start a service outside the legacy target set.');
      }
      return {
        installation: optionsForInstallationRecord(installation, obsoleteRecord),
        record: obsoleteRecord,
      };
    }),
  );
  const existing = obsolete.filter(
    (item): item is { installation: ServiceInstallOptions; record: ServiceInstallationRecord } =>
      item !== null,
  );
  const canonicalStatus = await installedService(canonicalOptions).status();
  if (canonicalStatus.running && !canonicalStatus.compatible) {
    throw new Error(
      `The canonical startup service uses incompatible control protocol ${canonicalStatus.protocolVersion}. It was left unchanged.`,
    );
  }
  const restartCanonical = !(canonicalStatus.running && canonicalStatus.activeRoutes > 0);
  if (!restartCanonical && existing.length === 0) {
    return { installed: true, record };
  }
  const runner = options.runner ?? executeCommand;
  if (platform === 'darwin') {
    await assertOwnedDefinition(
      record.definitionPath!,
      { options: canonicalOptions, record },
      true,
    );
    for (const item of existing) {
      await assertOwnedDefinition(
        item.record.definitionPath!,
        {
          options: item.installation,
          record: item.record,
        },
        true,
      );
    }
    const trackedInstallations = await inspectRunningInstallations([
      ...existing,
      ...(restartCanonical ? [{ installation: canonicalOptions, record }] : []),
    ]);
    const trackedExisting = trackedInstallations.filter(
      ({ record: trackedRecord }) => trackedRecord !== record,
    );
    const trackedCanonical = trackedInstallations.find(
      ({ record: trackedRecord }) => trackedRecord === record,
    );
    const rollbackWinnerIdentifier =
      (trackedCanonical?.wasRunning ? trackedCanonical.record.identifier : null) ??
      trackedExisting.find(({ wasRunning }) => wasRunning)?.record.identifier ??
      null;
    const rollbackExisting = trackedExisting.map((installation) => ({
      ...installation,
      wasRunning: installation.record.identifier === rollbackWinnerIdentifier,
    }));
    const rollbackCanonical = trackedCanonical
      ? {
          ...trackedCanonical,
          wasRunning: trackedCanonical.record.identifier === rollbackWinnerIdentifier,
        }
      : null;
    const controlClient = await stageMacosControlClient(options);
    try {
      await runElevatedCommands(options, runner, [
        ...macosQuiesceCommands(rollbackExisting, false, controlClient),
        ...(restartCanonical
          ? macosQuiesceCommands(
              [rollbackCanonical!],
              rollbackWinnerIdentifier === null,
              controlClient,
            )
          : []),
        ...macosBootoutCommands(trackedExisting, !restartCanonical),
        ...(restartCanonical
          ? [
              {
                command: 'launchctl',
                arguments_: ['enable', `system/${record.identifier}`],
                rollbackAfterSuccess: [
                  {
                    command: 'launchctl',
                    arguments_: ['disable', `system/${record.identifier}`],
                  },
                  {
                    command: 'launchctl',
                    arguments_: ['bootout', `system/${record.identifier}`],
                    allowFailure: true,
                  },
                  {
                    command: process.execPath,
                    arguments_: [
                      '--input-type=module',
                      '--eval',
                      MACOS_LAUNCHD_REMOVAL_WAIT_SOURCE,
                      record.identifier,
                    ],
                  },
                ],
              },
              {
                command: 'launchctl',
                arguments_: ['kickstart', '-k', `system/${record.identifier}`],
              },
              macosReadinessCommand(
                record.nodePath,
                record.cliPath,
                record.namespace,
                canonicalOptions.paths.socketPath,
              ),
            ]
          : []),
        ...macosCleanupCommands(trackedExisting),
      ]);
    } finally {
      await unlink(controlClient.cliPath).catch(() => undefined);
    }
  } else if (platform === 'linux') {
    await assertOwnedDefinition(
      record.definitionPath!,
      { options: canonicalOptions, record },
      true,
    );
    for (const item of existing) {
      await assertOwnedDefinition(
        item.record.definitionPath!,
        {
          options: item.installation,
          record: item.record,
        },
        true,
      );
    }
    const disabled: ObsoleteServiceInstallation[] = [];
    const stoppedIdentifiers = new Set<string>();
    let committed = false;
    try {
      if (restartCanonical && (await quiesceInstalledService(canonicalOptions))) {
        stoppedIdentifiers.add(record.identifier);
      }
      for (const item of existing) {
        if (await quiesceInstalledService(item.installation)) {
          stoppedIdentifiers.add(item.record.identifier);
        }
      }
      for (const item of existing) {
        disabled.push(item);
        await runElevatedCommand(options, runner, 'systemctl', [
          'disable',
          '--now',
          `${item.record.identifier}.service`,
        ]);
      }
      if (restartCanonical) {
        await runElevatedCommand(options, runner, 'systemctl', [
          'start',
          `${record.identifier}.service`,
        ]);
        await waitForStartupServiceReady(canonicalOptions);
      }
      committed = true;
      for (const item of existing) {
        await runElevatedCommand(options, runner, 'rm', ['-f', '--', item.record.definitionPath!]);
      }
      if (existing.length > 0) {
        await runElevatedCommand(options, runner, 'systemctl', ['daemon-reload']);
      }
      await Promise.all(
        existing.map(({ installation }) => removeInstallationRecords(installation)),
      );
      await Promise.all(
        existing.flatMap((item) =>
          item.record.runtimeDirectory
            ? [rm(item.record.runtimeDirectory, { recursive: true, force: true })]
            : [],
        ),
      );
    } catch (error) {
      if (!committed) {
        if (restartCanonical) {
          await runElevatedCommand(options, runner, 'systemctl', [
            'stop',
            `${record.identifier}.service`,
          ]).catch(() => undefined);
        }
        const restoredIdentifiers = new Set<string>();
        const restoreCanonical = stoppedIdentifiers.has(record.identifier);
        if (!restoreCanonical) {
          for (const item of [...disabled].reverse()) {
            if (restoredIdentifiers.size > 0 || !stoppedIdentifiers.has(item.record.identifier)) {
              continue;
            }
            try {
              await runElevatedCommand(options, runner, 'systemctl', [
                'enable',
                '--now',
                `${item.record.identifier}.service`,
              ]);
              restoredIdentifiers.add(item.record.identifier);
            } catch {
              await runElevatedCommand(options, runner, 'systemctl', [
                'disable',
                '--now',
                `${item.record.identifier}.service`,
              ]).catch(() => undefined);
              continue;
            }
          }
        }
        for (const item of [...existing].reverse()) {
          if (
            restoredIdentifiers.size > 0 ||
            !stoppedIdentifiers.has(item.record.identifier) ||
            disabled.some(
              ({ record: disabledRecord }) => disabledRecord.identifier === item.record.identifier,
            )
          ) {
            continue;
          }
          try {
            await runElevatedCommand(options, runner, 'systemctl', [
              'start',
              `${item.record.identifier}.service`,
            ]);
            restoredIdentifiers.add(item.record.identifier);
          } catch {
            await runElevatedCommand(options, runner, 'systemctl', [
              'disable',
              '--now',
              `${item.record.identifier}.service`,
            ]).catch(() => undefined);
          }
        }
        if (restartCanonical && restoredIdentifiers.size > 0) {
          await runElevatedCommand(options, runner, 'systemctl', [
            'disable',
            '--now',
            `${record.identifier}.service`,
          ]).catch(() => undefined);
        } else if (restartCanonical && restoreCanonical) {
          await runElevatedCommand(options, runner, 'systemctl', [
            'start',
            `${record.identifier}.service`,
          ]).catch(() => undefined);
        }
      }
      throw error;
    }
  } else if (platform === 'win32') {
    await assertOwnedWindowsStartupTask(runner, record);
    for (const item of existing) {
      await assertOwnedWindowsStartupTask(runner, item.record);
    }
    const stoppedIdentifiers = new Set<string>();
    const disabled: ObsoleteServiceInstallation[] = [];
    let committed = false;
    try {
      if (restartCanonical && (await quiesceInstalledService(canonicalOptions))) {
        stoppedIdentifiers.add(record.identifier);
      }
      for (const item of existing) {
        if (await quiesceInstalledService(item.installation)) {
          stoppedIdentifiers.add(item.record.identifier);
        }
      }
      for (const item of existing) {
        disabled.push(item);
        await runner('schtasks.exe', ['/Change', '/TN', item.record.identifier, '/Disable']);
      }
      if (restartCanonical) {
        await runner('schtasks.exe', ['/Change', '/TN', record.identifier, '/Enable']);
        await runner('schtasks.exe', ['/Run', '/TN', record.identifier]);
        await waitForStartupServiceReady(canonicalOptions);
      }
      committed = true;
      for (const item of existing) {
        await uninstallStartupService(item.installation);
      }
    } catch (error) {
      if (!committed) {
        if (restartCanonical) {
          await runner('schtasks.exe', ['/Change', '/TN', record.identifier, '/Disable']).catch(
            () => undefined,
          );
        }
        const restoredIdentifiers = new Set<string>();
        const restoreCanonical = stoppedIdentifiers.has(record.identifier);
        if (!restoreCanonical) {
          for (const item of [...disabled].reverse()) {
            if (restoredIdentifiers.size > 0 || !stoppedIdentifiers.has(item.record.identifier)) {
              continue;
            }
            try {
              await runner('schtasks.exe', ['/Change', '/TN', item.record.identifier, '/Enable']);
              await runner('schtasks.exe', ['/Run', '/TN', item.record.identifier]);
              restoredIdentifiers.add(item.record.identifier);
            } catch {
              await runner('schtasks.exe', [
                '/Change',
                '/TN',
                item.record.identifier,
                '/Disable',
              ]).catch(() => undefined);
              continue;
            }
          }
        }
        for (const item of [...existing].reverse()) {
          if (
            restoredIdentifiers.size > 0 ||
            !stoppedIdentifiers.has(item.record.identifier) ||
            disabled.some(
              ({ record: disabledRecord }) => disabledRecord.identifier === item.record.identifier,
            )
          ) {
            continue;
          }
          try {
            await runner('schtasks.exe', ['/Run', '/TN', item.record.identifier]);
            restoredIdentifiers.add(item.record.identifier);
            break;
          } catch {
            await runner('schtasks.exe', [
              '/Change',
              '/TN',
              item.record.identifier,
              '/Disable',
            ]).catch(() => undefined);
          }
        }
        if (restartCanonical && restoredIdentifiers.size === 0) {
          await runner('schtasks.exe', ['/Change', '/TN', record.identifier, '/Enable']).catch(
            () => undefined,
          );
          if (restoreCanonical) {
            await runner('schtasks.exe', ['/Run', '/TN', record.identifier]).catch(() => undefined);
          }
        }
      }
      throw error;
    }
  } else {
    throw new Error(`Unsupported service platform: ${platform}`);
  }
  if (platform !== 'win32') {
    await Promise.all(existing.map(({ installation }) => removeInstallationRecords(installation)));
  }
  return { installed: true, record };
}

export async function startOwnedStartupService(
  options: ServiceInstallOptions,
): Promise<ServiceInstallResult> {
  const record = await readRecord(options);
  if (!record) {
    throw new Error(`Startup service ${options.namespace} is not installed.`);
  }
  const installedOptions = optionsForInstallationRecord(options, record);
  const runner = options.runner ?? executeCommand;
  if (record.platform === 'darwin') {
    await assertOwnedDefinition(
      record.definitionPath!,
      { options: installedOptions, record },
      true,
    );
    await runElevatedCommands(options, runner, [
      { command: 'launchctl', arguments_: ['enable', `system/${record.identifier}`] },
      { command: 'launchctl', arguments_: ['kickstart', '-k', `system/${record.identifier}`] },
    ]);
  } else if (record.platform === 'linux') {
    await assertOwnedDefinition(
      record.definitionPath!,
      { options: installedOptions, record },
      true,
    );
    await runElevatedCommand(options, runner, 'systemctl', [
      'start',
      `${record.identifier}.service`,
    ]);
  } else if (record.platform === 'win32') {
    await assertOwnedWindowsStartupTask(runner, record);
    await runner('schtasks.exe', ['/Run', '/TN', record.identifier]);
  } else {
    throw new Error(`Unsupported service platform: ${record.platform}`);
  }
  return { installed: true, record };
}

export async function uninstallStartupService(
  options: ServiceInstallOptions,
): Promise<ServiceInstallResult> {
  const record = await readRecord(options);
  if (!record) {
    return { installed: false, record: null };
  }
  const installedOptions = optionsForInstallationRecord(options, record);
  const runner = options.runner ?? executeCommand;
  if (record.platform === 'darwin') {
    await assertOwnedDefinition(
      record.definitionPath!,
      { options: installedOptions, record },
      true,
    );
    const trackedInstallation = (
      await inspectRunningInstallations([{ installation: installedOptions, record }])
    )[0]!;
    const controlClient = await stageMacosControlClient(options);
    try {
      const commands: ServiceInstallElevatedCommand[] = [
        ...macosQuiesceCommands([trackedInstallation], true, controlClient),
        {
          command: 'launchctl',
          arguments_: ['bootout', `system/${record.identifier}`],
          allowFailure: true,
        },
        {
          command: process.execPath,
          arguments_: [
            '--input-type=module',
            '--eval',
            MACOS_LAUNCHD_REMOVAL_WAIT_SOURCE,
            record.identifier,
          ],
        },
        ...macosCleanupCommands([trackedInstallation]),
      ];
      await runElevatedCommands(options, runner, commands);
    } finally {
      await unlink(controlClient.cliPath).catch(() => undefined);
    }
  } else if (record.platform === 'linux') {
    await assertOwnedDefinition(
      record.definitionPath!,
      { options: installedOptions, record },
      true,
    );
    await quiesceInstalledService(installedOptions);
    async function runElevated(command: string, arguments_: string[]): Promise<void> {
      await runElevatedCommand(options, runner, command, arguments_);
    }
    await runElevated('systemctl', ['disable', '--now', `${record.identifier}.service`]);
    await runElevated('rm', ['-f', '--', record.definitionPath!]);
    await runElevated('systemctl', ['daemon-reload']);
    await removeInstallationRecords(options);
    if (record.runtimeDirectory) {
      await rm(record.runtimeDirectory, { recursive: true, force: true });
    }
  } else if (record.platform === 'win32') {
    await assertOwnedWindowsStartupTask(runner, record);
    await quiesceInstalledService(installedOptions);
    await runner('schtasks.exe', ['/End', '/TN', record.identifier]).catch(() => undefined);
    await runner('schtasks.exe', ['/Delete', '/TN', record.identifier, '/F']);
    await removeInstallationRecords(options);
    if (record.runtimeDirectory) {
      await rm(record.runtimeDirectory, {
        recursive: true,
        force: true,
        maxRetries: 10,
        retryDelay: 100,
      });
    }
  }
  await removeInstallationRecords(options);
  return { installed: false, record };
}
