import { createHash } from 'node:crypto';
import { chmod, copyFile, mkdir, readFile, rename, rm, unlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import type {
  ServiceInstallCommandResult,
  ServiceInstallCommandRunner,
  ServiceInstallElevatedCommand,
  ServiceInstallationRecord,
  ServiceInstallOptions,
  ServiceInstallResult,
} from './interfaces/service-install-options.js';
import type { ServiceRuntimeConfiguration } from './interfaces/service-runtime-configuration.js';
import { executeCommand } from './command-runner.js';
import { ensureStatePaths, sanitizeNamespace } from './state-paths.js';

const OWNER_MARKER = 'generated by @vampaz/vite-plugin-local-tls';
const MACOS_ELEVATED_SEQUENCE_SOURCE = [
  'import { spawnSync } from "node:child_process";',
  'const commands = JSON.parse(process.argv[1]);',
  'for (const request of commands) {',
  '  const child = spawnSync("sudo", ["--", request.command, ...request.arguments_], { stdio: "inherit" });',
  '  if (child.error) console.error(child.error.message);',
  '  if ((child.error || child.status !== 0) && !request.allowFailure) process.exit(child.status ?? 1);',
  '}',
].join('\n');

const MACOS_LAUNCHD_REMOVAL_WAIT_SOURCE = [
  'import { spawnSync } from "node:child_process";',
  'const identifier = process.argv[1];',
  'const deadline = Date.now() + 10_000;',
  'let absentChecks = 0;',
  'while (Date.now() < deadline) {',
  '  const child = spawnSync("launchctl", ["print", `system/${identifier}`], { stdio: "ignore" });',
  '  if (child.error) { console.error(child.error.message); process.exit(1); }',
  '  absentChecks = child.status === 0 ? 0 : absentChecks + 1;',
  '  if (absentChecks === 2) process.exit(0);',
  '  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 100);',
  '}',
  'console.error(`Timed out waiting for launchd to remove ${identifier}.`);',
  'process.exit(1);',
].join('\n');

function xmlEscape(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

function systemdQuote(value: string): string {
  return `"${value.replaceAll('%', '%%').replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;
}

function windowsQuote(value: string): string {
  return `"${value.replaceAll(/(\\*)"/g, '$1$1\\"').replaceAll(/(\\+)$/g, '$1$1')}"`;
}

function validateDefinitionValue(value: string, label: string): string {
  const hasControlCharacter = [...value].some((character) => {
    const codePoint = character.codePointAt(0) ?? 0;
    return codePoint < 32 || codePoint === 127;
  });
  if (!value || hasControlCharacter) {
    throw new Error(`${label} contains unsupported control characters.`);
  }
  return value;
}

function safeServiceKey(options: ServiceInstallOptions): string {
  const platform = options.platform ?? process.platform;
  const key = sanitizeNamespace(options.namespace);
  if (!/^[a-z0-9-]{1,40}$/.test(key)) {
    throw new Error(`Unsafe service namespace: ${key}`);
  }
  validateDefinitionValue(options.namespace, 'Service namespace');
  if (options.namespace.length > 256) {
    throw new Error('Service namespace exceeds 256 characters.');
  }
  validateDefinitionValue(options.nodePath, 'Node path');
  validateDefinitionValue(options.cliPath, 'CLI path');
  validateDefinitionValue(options.homeDirectory ?? os.homedir(), 'Home directory');
  validateDefinitionValue(options.username ?? os.userInfo().username, 'Username');
  validateDefinitionValue(options.paths.stateDirectory, 'State directory');
  validateDefinitionValue(options.paths.runtimeDirectory, 'Runtime directory');
  validateDefinitionValue(options.paths.socketPath, 'Control socket');
  if (options.controlSocket) {
    validateDefinitionValue(options.controlSocket, 'Control socket');
    if (options.controlSocket.length > 4096) {
      throw new Error('Control socket exceeds 4096 characters.');
    }
  }
  if (options.runtimeInstallDirectory) {
    validateDefinitionValue(options.runtimeInstallDirectory, 'Service runtime directory');
  }
  if (
    platform === 'linux' &&
    !/^[a-zA-Z_][a-zA-Z0-9_-]*\$?$/.test(options.username ?? os.userInfo().username)
  ) {
    throw new Error('Username cannot be represented safely in a systemd service.');
  }
  if (platform === 'darwin') {
    for (const [label, value] of [
      ['User ID', options.uid ?? os.userInfo().uid],
      ['Group ID', options.gid ?? os.userInfo().gid],
    ] as const) {
      if (!Number.isSafeInteger(value) || value < 0) {
        throw new Error(`${label} must be a non-negative integer.`);
      }
    }
  }
  return key;
}

function recordPath(options: ServiceInstallOptions): string {
  return path.join(options.paths.stateDirectory, 'service-install.json');
}

function serviceIdentifier(platform: NodeJS.Platform, key: string): string {
  return platform === 'darwin'
    ? `com.vampaz.vite-local-tls.${key}`
    : platform === 'win32'
      ? `Vite Local TLS\\${key}`
      : `vite-local-tls-${key}`;
}

function expectedDefinitionPath(
  options: ServiceInstallOptions,
  platform: NodeJS.Platform,
  identifier: string,
): string | null {
  if (platform === 'darwin') {
    return path.join(
      options.definitionDirectory ?? '/Library/LaunchDaemons',
      `${identifier}.plist`,
    );
  }
  if (platform === 'linux') {
    return path.join(options.definitionDirectory ?? '/etc/systemd/system', `${identifier}.service`);
  }
  return null;
}

function expectedRuntimeDirectory(
  options: ServiceInstallOptions,
  platform: NodeJS.Platform,
  key: string,
): string {
  if (options.runtimeInstallDirectory) {
    return options.runtimeInstallDirectory;
  }
  if (platform === 'darwin') {
    return path.join('/Library/Application Support/vite-plugin-local-tls', key);
  }
  if (platform === 'win32') {
    return path.join(
      path.dirname(path.dirname(options.paths.stateDirectory)),
      'vlt',
      windowsRuntimeKey(key),
    );
  }
  return path.join(options.paths.stateDirectory, 'service-runtime');
}

function windowsConfigurationPath(runtimeDirectory: string): string {
  return path.join(runtimeDirectory, 's.json');
}

function windowsRuntimeKey(key: string): string {
  return createHash('sha256').update(key).digest('hex').slice(0, 12);
}

function windowsTaskPath(filePath: string): string {
  const localAppData = process.env.LOCALAPPDATA;
  if (!localAppData) {
    return filePath;
  }
  const relativePath = path.win32.relative(localAppData, filePath);
  if (relativePath.startsWith('..') || path.win32.isAbsolute(relativePath)) {
    return filePath;
  }
  return path.win32.join('%LOCALAPPDATA%', relativePath);
}

function windowsTaskCommand(nodePath: string, cliPath: string, configurationPath: string): string {
  return `${windowsQuote(windowsTaskPath(nodePath))} ${windowsTaskArguments(
    cliPath,
    configurationPath,
  )}`;
}

function windowsTaskArguments(cliPath: string, configurationPath: string): string {
  return [
    windowsQuote(windowsTaskPath(cliPath)),
    'proxy',
    'start',
    '--service',
    '--service-config',
    windowsQuote(windowsTaskPath(configurationPath)),
  ].join(' ');
}

function assertExpectedRecord(
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
): void {
  const platform = options.platform ?? process.platform;
  const key = safeServiceKey(options);
  const identifier = serviceIdentifier(platform, key);
  const definitionPath = expectedDefinitionPath(options, platform, identifier);
  if (record.identifier !== identifier || record.definitionPath !== definitionPath) {
    throw new Error('Service installation record contains unexpected system targets.');
  }
  if (!record.runtimeDirectory) {
    return;
  }
  const runtimeDirectory = expectedRuntimeDirectory(options, platform, key);
  const cliPath = path.join(
    runtimeDirectory,
    platform === 'darwin' ? 'cli.js' : platform === 'win32' ? 'c.js' : `cli-${key}.js`,
  );
  const nodePath = path.join(runtimeDirectory, platform === 'win32' ? 'n.exe' : 'node');
  if (
    record.runtimeDirectory !== runtimeDirectory ||
    record.cliPath !== cliPath ||
    record.nodePath !== nodePath
  ) {
    throw new Error('Service installation record contains an unexpected runtime target.');
  }
}

async function readRecord(
  options: ServiceInstallOptions,
): Promise<ServiceInstallationRecord | null> {
  try {
    const record = JSON.parse(
      await readFile(recordPath(options), 'utf8'),
    ) as ServiceInstallationRecord;
    if (
      record.version !== 1 ||
      record.namespace !== options.namespace ||
      record.platform !== (options.platform ?? process.platform)
    ) {
      throw new Error('Service installation record does not match this namespace and platform.');
    }
    assertExpectedRecord(options, record);
    return record;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return null;
    }
    throw error;
  }
}

export async function isStartupServiceCurrent(options: ServiceInstallOptions): Promise<boolean> {
  const record = await readRecord(options);
  if (!record) {
    return true;
  }
  try {
    const [currentCli, installedCli] = await Promise.all([
      readFile(options.cliPath),
      readFile(record.cliPath),
    ]);
    return currentCli.equals(installedCli);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return false;
    }
    throw error;
  }
}

async function writeRecord(
  options: ServiceInstallOptions,
  record: ServiceInstallationRecord,
): Promise<void> {
  const finalPath = recordPath(options);
  const temporaryPath = `${finalPath}.${process.pid}.tmp`;
  await writeFile(temporaryPath, `${JSON.stringify(record, null, 2)}\n`, { mode: 0o600 });
  await rename(temporaryPath, finalPath);
}

async function assertOwnedDefinition(definitionPath: string): Promise<void> {
  try {
    const contents = await readFile(definitionPath, 'utf8');
    if (!contents.includes(OWNER_MARKER)) {
      throw new Error(`Refusing to overwrite unrelated service definition: ${definitionPath}`);
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
  }
}

function launchdDefinition(options: ServiceInstallOptions, identifier: string): string {
  const user = os.userInfo();
  const username = options.username ?? user.username;
  const uid = options.uid ?? user.uid;
  const gid = options.gid ?? user.gid;
  const arguments_ = [
    options.nodePath,
    options.cliPath,
    'proxy',
    'start',
    '--service',
    '--namespace',
    options.namespace,
    '--run-as-uid',
    String(uid),
    '--run-as-gid',
    String(gid),
  ];
  if (options.controlSocket) {
    arguments_.push('--control-socket', options.controlSocket);
  }
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    '<dict>',
    `  <!-- ${OWNER_MARKER} -->`,
    '  <key>Label</key>',
    `  <string>${xmlEscape(identifier)}</string>`,
    '  <key>ProgramArguments</key>',
    '  <array>',
    ...arguments_.map((argument) => `    <string>${xmlEscape(argument)}</string>`),
    '  </array>',
    '  <key>EnvironmentVariables</key>',
    '  <dict>',
    '    <key>HOME</key>',
    `    <string>${xmlEscape(options.homeDirectory ?? os.homedir())}</string>`,
    '    <key>USER</key>',
    `    <string>${xmlEscape(username)}</string>`,
    '    <key>LOGNAME</key>',
    `    <string>${xmlEscape(username)}</string>`,
    '    <key>VITE_LOCAL_TLS_USER_ID</key>',
    `    <string>${uid}</string>`,
    '    <key>VITE_LOCAL_TLS_RUNTIME_DIRECTORY</key>',
    `    <string>${xmlEscape(options.paths.runtimeDirectory)}</string>`,
    '  </dict>',
    '  <key>RunAtLoad</key>',
    '  <true/>',
    '  <key>KeepAlive</key>',
    '  <true/>',
    '  <key>ProcessType</key>',
    '  <string>Background</string>',
    '  <key>StandardOutPath</key>',
    `  <string>${xmlEscape(path.join(options.paths.stateDirectory, 'service.log'))}</string>`,
    '  <key>StandardErrorPath</key>',
    `  <string>${xmlEscape(path.join(options.paths.stateDirectory, 'service-error.log'))}</string>`,
    '</dict>',
    '</plist>',
    '',
  ].join('\n');
}

async function installUserRuntime(
  options: ServiceInstallOptions,
  key: string,
): Promise<{ nodePath: string; cliPath: string; runtimeDirectory: string }> {
  const runtimeDirectory =
    options.runtimeInstallDirectory ??
    expectedRuntimeDirectory(
      options,
      options.platform ?? process.platform,
      safeServiceKey(options),
    );
  const nodePath = path.join(
    runtimeDirectory,
    (options.platform ?? process.platform) === 'win32' ? 'n.exe' : 'node',
  );
  const cliPath = path.join(
    runtimeDirectory,
    (options.platform ?? process.platform) === 'win32' ? 'c.js' : `cli-${key}.js`,
  );
  await mkdir(runtimeDirectory, { recursive: true, mode: 0o700 });
  await copyFile(options.nodePath, nodePath);
  await copyFile(options.cliPath, cliPath);
  if ((options.platform ?? process.platform) !== 'win32') {
    await chmod(nodePath, 0o700);
    await chmod(cliPath, 0o700);
  }
  return { nodePath, cliPath, runtimeDirectory };
}

function systemdDefinition(options: ServiceInstallOptions): string {
  const username = options.username ?? os.userInfo().username;
  const arguments_ = [
    options.nodePath,
    options.cliPath,
    'proxy',
    'start',
    '--service',
    '--namespace',
    options.namespace,
  ];
  if (options.controlSocket) {
    arguments_.push('--control-socket', options.controlSocket);
  }
  return [
    `# ${OWNER_MARKER}`,
    '[Unit]',
    'Description=Vite local TLS proxy',
    'After=network.target',
    '',
    '[Service]',
    'Type=simple',
    `User=${username}`,
    `Environment=HOME=${systemdQuote(options.homeDirectory ?? os.homedir())}`,
    `Environment=VITE_LOCAL_TLS_RUNTIME_DIRECTORY=${systemdQuote(options.paths.runtimeDirectory)}`,
    `ExecStart=${arguments_.map(systemdQuote).join(' ')}`,
    'Restart=on-failure',
    'RestartSec=1',
    'AmbientCapabilities=CAP_NET_BIND_SERVICE',
    'CapabilityBoundingSet=CAP_NET_BIND_SERVICE',
    'NoNewPrivileges=true',
    'PrivateTmp=false',
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    '',
  ].join('\n');
}

function usesSudo(options: ServiceInstallOptions): boolean {
  return options.useSudo === true || (options.useSudo !== false && process.getuid?.() !== 0);
}

function runElevatedCommand(
  options: ServiceInstallOptions,
  runner: ServiceInstallCommandRunner,
  command: string,
  arguments_: string[],
): Promise<ServiceInstallCommandResult> {
  const useSudo = usesSudo(options);
  if (!useSudo) {
    return runner(command, arguments_);
  }
  return runner('sudo', ['--', command, ...arguments_], { interactive: true });
}

async function runElevatedCommands(
  options: ServiceInstallOptions,
  runner: ServiceInstallCommandRunner,
  commands: ServiceInstallElevatedCommand[],
): Promise<void> {
  if ((options.platform ?? process.platform) === 'darwin' && usesSudo(options) && !process.env.CI) {
    await runner(
      process.execPath,
      ['--input-type=module', '--eval', MACOS_ELEVATED_SEQUENCE_SOURCE, JSON.stringify(commands)],
      { interactive: true },
    );
    return;
  }
  for (const request of commands) {
    try {
      await runElevatedCommand(options, runner, request.command, request.arguments_);
    } catch (error) {
      if (!request.allowFailure) {
        throw error;
      }
    }
  }
}

async function installMacos(
  options: ServiceInstallOptions,
  runner: ServiceInstallCommandRunner,
  identifier: string,
): Promise<{
  definitionPath: string;
  nodePath: string;
  cliPath: string;
  runtimeDirectory: string;
}> {
  const definitionPath = path.join(
    options.definitionDirectory ?? '/Library/LaunchDaemons',
    `${identifier}.plist`,
  );
  const runtimeDirectory = expectedRuntimeDirectory(options, 'darwin', safeServiceKey(options));
  const nodePath = path.join(runtimeDirectory, 'node');
  const cliPath = path.join(runtimeDirectory, 'cli.js');
  const temporaryDefinitionPath = path.join(
    options.paths.stateDirectory,
    `${identifier}.plist.tmp`,
  );
  await assertOwnedDefinition(definitionPath);
  await writeFile(
    temporaryDefinitionPath,
    launchdDefinition({ ...options, nodePath, cliPath }, identifier),
    { mode: 0o600 },
  );
  try {
    await runElevatedCommands(options, runner, [
      { command: 'mkdir', arguments_: ['-p', runtimeDirectory] },
      { command: 'install', arguments_: ['-m', '0755', options.nodePath, nodePath] },
      { command: 'install', arguments_: ['-m', '0644', options.cliPath, cliPath] },
      {
        command: 'install',
        arguments_: ['-m', '0644', temporaryDefinitionPath, definitionPath],
      },
      {
        command: 'launchctl',
        arguments_: ['bootout', `system/${identifier}`],
        allowFailure: true,
      },
      {
        command: process.execPath,
        arguments_: [
          '--input-type=module',
          '--eval',
          MACOS_LAUNCHD_REMOVAL_WAIT_SOURCE,
          identifier,
        ],
      },
      { command: 'launchctl', arguments_: ['bootstrap', 'system', definitionPath] },
      { command: 'launchctl', arguments_: ['enable', `system/${identifier}`] },
      { command: 'launchctl', arguments_: ['kickstart', '-k', `system/${identifier}`] },
    ]);
  } finally {
    await unlink(temporaryDefinitionPath).catch(() => undefined);
  }
  return { definitionPath, nodePath, cliPath, runtimeDirectory };
}

async function installLinux(
  options: ServiceInstallOptions,
  runner: ServiceInstallCommandRunner,
  identifier: string,
): Promise<{
  definitionPath: string;
  nodePath: string;
  cliPath: string;
  runtimeDirectory: string;
}> {
  const definitionPath = path.join(
    options.definitionDirectory ?? '/etc/systemd/system',
    `${identifier}.service`,
  );
  await assertOwnedDefinition(definitionPath);
  const runtime = await installUserRuntime(options, safeServiceKey(options));
  const serviceOptions = { ...options, nodePath: runtime.nodePath, cliPath: runtime.cliPath };
  const temporaryPath = path.join(options.paths.stateDirectory, `${identifier}.service.tmp`);
  await writeFile(temporaryPath, systemdDefinition(serviceOptions), { mode: 0o600 });
  async function runElevated(
    command: string,
    arguments_: string[],
  ): Promise<ServiceInstallCommandResult> {
    return runElevatedCommand(options, runner, command, arguments_);
  }
  try {
    await runElevated('install', ['-m', '0644', '--', temporaryPath, definitionPath]);
    await runElevated('systemctl', ['daemon-reload']);
    await runElevated('systemctl', ['enable', '--now', `${identifier}.service`]);
  } finally {
    await unlink(temporaryPath).catch(() => undefined);
  }
  return {
    definitionPath,
    nodePath: runtime.nodePath,
    cliPath: runtime.cliPath,
    runtimeDirectory: runtime.runtimeDirectory,
  };
}

async function windowsTaskExists(
  runner: ServiceInstallCommandRunner,
  identifier: string,
): Promise<boolean> {
  return runner('schtasks.exe', ['/Query', '/TN', identifier])
    .then(() => true)
    .catch(() => false);
}

async function installWindows(
  options: ServiceInstallOptions,
  runner: ServiceInstallCommandRunner,
  identifier: string,
): Promise<{ nodePath: string; cliPath: string; runtimeDirectory: string }> {
  if (!(await readRecord(options)) && (await windowsTaskExists(runner, identifier))) {
    throw new Error(`Refusing to replace unrelated scheduled task: ${identifier}`);
  }
  const runtime = await installUserRuntime(options, safeServiceKey(options));
  const configurationPath = windowsConfigurationPath(runtime.runtimeDirectory);
  const configuration: ServiceRuntimeConfiguration = {
    version: 1,
    owner: '@vampaz/vite-plugin-local-tls',
    namespace: options.namespace,
    controlSocket: options.controlSocket ?? null,
  };
  await writeFile(configurationPath, `${JSON.stringify(configuration, null, 2)}\n`, {
    mode: 0o600,
  });
  const command = windowsTaskCommand(runtime.nodePath, runtime.cliPath, configurationPath);
  if (command.length > 261) {
    throw new Error('Windows Task Scheduler command exceeds its 261-character limit.');
  }
  await runner('schtasks.exe', [
    '/Create',
    '/TN',
    identifier,
    '/TR',
    command,
    '/SC',
    'ONLOGON',
    '/RL',
    'LIMITED',
    '/F',
  ]);
  await runner('schtasks.exe', ['/Run', '/TN', identifier]);
  return runtime;
}

export async function installStartupService(
  options: ServiceInstallOptions,
): Promise<ServiceInstallResult> {
  await ensureStatePaths(options.paths);
  const platform = options.platform ?? process.platform;
  const key = safeServiceKey(options);
  const runner = options.runner ?? executeCommand;
  const identifier = serviceIdentifier(platform, key);
  let definitionPath: string | null = null;
  let installedNodePath = options.nodePath;
  let installedCliPath = options.cliPath;
  let runtimeDirectory: string | undefined;
  if (platform === 'darwin') {
    const installed = await installMacos(options, runner, identifier);
    definitionPath = installed.definitionPath;
    installedNodePath = installed.nodePath;
    installedCliPath = installed.cliPath;
    runtimeDirectory = installed.runtimeDirectory;
  } else if (platform === 'linux') {
    const installed = await installLinux(options, runner, identifier);
    definitionPath = installed.definitionPath;
    installedNodePath = installed.nodePath;
    installedCliPath = installed.cliPath;
    runtimeDirectory = installed.runtimeDirectory;
  } else if (platform === 'win32') {
    const installed = await installWindows(options, runner, identifier);
    installedNodePath = installed.nodePath;
    installedCliPath = installed.cliPath;
    runtimeDirectory = installed.runtimeDirectory;
  } else {
    throw new Error(`Unsupported service platform: ${platform}`);
  }
  const record: ServiceInstallationRecord = {
    version: 1,
    platform,
    namespace: options.namespace,
    identifier,
    definitionPath,
    nodePath: installedNodePath,
    cliPath: installedCliPath,
    runtimeDirectory,
    controlSocket: options.controlSocket ?? null,
    installedAt: new Date().toISOString(),
  };
  await writeRecord(options, record);
  return { installed: true, record };
}

export async function uninstallStartupService(
  options: ServiceInstallOptions,
): Promise<ServiceInstallResult> {
  const record = await readRecord(options);
  if (!record) {
    return { installed: false, record: null };
  }
  const runner = options.runner ?? executeCommand;
  if (record.platform === 'darwin') {
    await assertOwnedDefinition(record.definitionPath!);
    const commands: ServiceInstallElevatedCommand[] = [
      {
        command: 'launchctl',
        arguments_: ['bootout', `system/${record.identifier}`],
        allowFailure: true,
      },
      {
        command: process.execPath,
        arguments_: [
          '--input-type=module',
          '--eval',
          MACOS_LAUNCHD_REMOVAL_WAIT_SOURCE,
          record.identifier,
        ],
      },
      { command: 'rm', arguments_: ['-f', record.definitionPath!] },
    ];
    if (record.runtimeDirectory) {
      commands.push({ command: 'rm', arguments_: ['-rf', record.runtimeDirectory] });
    }
    await runElevatedCommands(options, runner, commands);
  } else if (record.platform === 'linux') {
    await assertOwnedDefinition(record.definitionPath!);
    async function runElevated(command: string, arguments_: string[]): Promise<void> {
      await runElevatedCommand(options, runner, command, arguments_);
    }
    await runElevated('systemctl', ['disable', '--now', `${record.identifier}.service`]);
    await runElevated('rm', ['-f', '--', record.definitionPath!]);
    await runElevated('systemctl', ['daemon-reload']);
    if (record.runtimeDirectory) {
      await rm(record.runtimeDirectory, { recursive: true, force: true });
    }
  } else if (record.platform === 'win32') {
    const task = await runner('schtasks.exe', ['/Query', '/TN', record.identifier, '/XML']);
    const configurationPath = windowsConfigurationPath(record.runtimeDirectory!);
    const configuration = JSON.parse(
      await readFile(configurationPath, 'utf8'),
    ) as ServiceRuntimeConfiguration;
    const ownsConfiguration =
      configuration.version === 1 &&
      configuration.owner === '@vampaz/vite-plugin-local-tls' &&
      configuration.namespace === record.namespace &&
      configuration.controlSocket === record.controlSocket;
    const taskPath = windowsTaskPath(record.nodePath);
    const taskArguments = windowsTaskArguments(record.cliPath, configurationPath);
    const ownsTask =
      ownsConfiguration &&
      [taskPath, taskArguments].every(
        (value) => task.stdout.includes(value) || task.stdout.includes(xmlEscape(value)),
      );
    if (!ownsTask) {
      throw new Error(`Refusing to remove unrelated scheduled task: ${record.identifier}`);
    }
    await runner('schtasks.exe', ['/End', '/TN', record.identifier]).catch(() => undefined);
    await runner('schtasks.exe', ['/Delete', '/TN', record.identifier, '/F']);
    if (record.runtimeDirectory) {
      await rm(record.runtimeDirectory, {
        recursive: true,
        force: true,
        maxRetries: 10,
        retryDelay: 100,
      });
    }
  }
  await unlink(recordPath(options));
  return { installed: false, record };
}
