import { access, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { StatePaths } from './interfaces/state-paths.js';
import {
  getStartupServiceUpdateStatus,
  installStartupService,
  isStartupServiceCurrent,
  STARTUP_SERVICE_OWNER_MARKER,
} from './service-install.js';

let temporaryDirectory: string;

function statePaths(): StatePaths {
  const stateDirectory = path.join(temporaryDirectory, 'state');
  const runtimeDirectory = path.join(temporaryDirectory, 'runtime');
  return {
    stateDirectory,
    runtimeDirectory,
    socketPath: path.join(runtimeDirectory, 'control.sock'),
    lockPath: path.join(runtimeDirectory, 'startup.lock'),
    stateFile: path.join(stateDirectory, 'service.json'),
    certificateDirectory: path.join(stateDirectory, 'certificates'),
    importedCertificateDirectory: path.join(stateDirectory, 'imported'),
    caKeyPath: path.join(stateDirectory, 'ca-key.pem'),
    caCertificatePath: path.join(stateDirectory, 'ca.pem'),
    caStatePath: path.join(stateDirectory, 'ca.json'),
  };
}

beforeEach(async () => {
  temporaryDirectory = await mkdtemp(path.join(os.tmpdir(), 'vite-local-tls-version-'));
});

afterEach(async () => {
  await rm(temporaryDirectory, { recursive: true, force: true });
});

describe('startup service version compatibility', () => {
  it('stores a private v2 record that older byte-comparison clients cannot downgrade', async () => {
    const cliPath = path.join(temporaryDirectory, 'cli.js');
    let installedDefinition = '';
    const options = {
      platform: 'linux' as const,
      namespace: 'default',
      paths: statePaths(),
      nodePath: process.execPath,
      cliPath,
      currentVersion: '1.2.3',
      definitionDirectory: path.join(temporaryDirectory, 'systemd'),
      runner: vi.fn(async (_command: string, arguments_: string[]) => {
        const temporaryPath = arguments_.find((argument) => argument.endsWith('.service.tmp'));
        if (temporaryPath) {
          installedDefinition = await readFile(temporaryPath, 'utf8');
        }
        return { stdout: '', stderr: '' };
      }),
      useSudo: false,
    };
    await writeFile(cliPath, "console.log('1.2.3');\n");

    const result = await installStartupService(options);

    expect(result.record).toMatchObject({
      version: 2,
      packageVersion: '1.2.3',
      namespace: 'default',
    });
    await expect(
      readFile(path.join(options.paths.stateDirectory, 'service-install-v2.json'), 'utf8'),
    ).resolves.toContain('"packageVersion": "1.2.3"');
    await expect(
      access(path.join(options.paths.stateDirectory, 'service-install.json')),
    ).rejects.toThrow();
    expect(installedDefinition).toContain(STARTUP_SERVICE_OWNER_MARKER);
    expect(installedDefinition).not.toContain('generated by @vampaz/vite-plugin-local-tls');
  });

  it('updates older services, reuses newer services, and verifies equal-version bytes', async () => {
    const cliPath = path.join(temporaryDirectory, 'cli.js');
    const options = {
      platform: 'linux' as const,
      namespace: 'default',
      paths: statePaths(),
      nodePath: process.execPath,
      cliPath,
      currentVersion: '2.0.0',
      definitionDirectory: path.join(temporaryDirectory, 'systemd'),
      runner: vi.fn(async () => ({ stdout: '', stderr: '' })),
      useSudo: false,
    };
    await writeFile(cliPath, "console.log('2.0.0');\n");
    await installStartupService(options);

    await expect(isStartupServiceCurrent({ ...options, currentVersion: '2.0.1' })).resolves.toBe(
      false,
    );
    await expect(isStartupServiceCurrent({ ...options, currentVersion: '1.9.9' })).resolves.toBe(
      true,
    );
    await expect(isStartupServiceCurrent(options)).resolves.toBe(true);

    await writeFile(cliPath, "console.log('tampered');\n");
    await expect(isStartupServiceCurrent(options)).resolves.toBe(false);
  });

  it('updates a legacy canonical record that points at an alternate control channel', async () => {
    const cliPath = path.join(temporaryDirectory, 'cli.js');
    const options = {
      platform: 'linux' as const,
      namespace: 'default',
      paths: statePaths(),
      nodePath: process.execPath,
      cliPath,
      currentVersion: '2.0.0',
      definitionDirectory: path.join(temporaryDirectory, 'systemd'),
      runner: vi.fn(async () => ({ stdout: '', stderr: '' })),
      useSudo: false,
    };
    await writeFile(cliPath, "console.log('2.0.0');\n");
    await installStartupService(options);
    const recordPath = path.join(options.paths.stateDirectory, 'service-install-v2.json');
    const record = JSON.parse(await readFile(recordPath, 'utf8')) as Record<string, unknown>;
    record.controlSocket = '/tmp/legacy-control.sock';
    await writeFile(recordPath, `${JSON.stringify(record, null, 2)}\n`);

    await expect(getStartupServiceUpdateStatus(options)).resolves.toBe('modified');
    await expect(isStartupServiceCurrent(options)).resolves.toBe(false);
  });

  it('repairs an equal-version record that advertises a different control protocol', async () => {
    const cliPath = path.join(temporaryDirectory, 'cli.js');
    const options = {
      platform: 'linux' as const,
      namespace: 'default',
      paths: statePaths(),
      nodePath: process.execPath,
      cliPath,
      currentVersion: '2.0.0',
      definitionDirectory: path.join(temporaryDirectory, 'systemd'),
      runner: vi.fn(async () => ({ stdout: '', stderr: '' })),
      useSudo: false,
    };
    await writeFile(cliPath, "console.log('2.0.0');\n");
    await installStartupService(options);
    const recordPath = path.join(options.paths.stateDirectory, 'service-install-v2.json');
    const record = JSON.parse(await readFile(recordPath, 'utf8')) as Record<string, unknown>;
    record.protocolVersion = 2;
    await writeFile(recordPath, `${JSON.stringify(record, null, 2)}\n`);

    await expect(getStartupServiceUpdateStatus(options)).resolves.toBe('modified');
    await expect(isStartupServiceCurrent(options)).resolves.toBe(false);
  });

  it('repairs an installation record with an invalid package version', async () => {
    const cliPath = path.join(temporaryDirectory, 'cli.js');
    const options = {
      platform: 'linux' as const,
      namespace: 'default',
      paths: statePaths(),
      nodePath: process.execPath,
      cliPath,
      currentVersion: '2.0.0',
      definitionDirectory: path.join(temporaryDirectory, 'systemd'),
      runner: vi.fn(async () => ({ stdout: '', stderr: '' })),
      useSudo: false,
    };
    await writeFile(cliPath, "console.log('2.0.0');\n");
    await installStartupService(options);
    const recordPath = path.join(options.paths.stateDirectory, 'service-install-v2.json');
    const record = JSON.parse(await readFile(recordPath, 'utf8')) as Record<string, unknown>;
    record.packageVersion = 'not-semver';
    await writeFile(recordPath, `${JSON.stringify(record, null, 2)}\n`);

    await expect(getStartupServiceUpdateStatus(options)).resolves.toBe('modified');
    await expect(isStartupServiceCurrent(options)).resolves.toBe(false);
  });

  it('starts a newer stopped service without replacing its runtime with older package bytes', async () => {
    const cliPath = path.join(temporaryDirectory, 'cli.js');
    const definitionDirectory = path.join(temporaryDirectory, 'systemd');
    const runner = vi.fn(async () => ({ stdout: '', stderr: '' }));
    const options = {
      platform: 'linux' as const,
      namespace: 'default',
      paths: statePaths(),
      nodePath: process.execPath,
      cliPath,
      currentVersion: '3.0.0',
      definitionDirectory,
      runner,
      useSudo: false,
    };
    await writeFile(cliPath, "console.log('newer');\n");
    const installed = await installStartupService(options);
    await mkdir(definitionDirectory, { recursive: true });
    await writeFile(
      installed.record!.definitionPath!,
      [
        `# ${STARTUP_SERVICE_OWNER_MARKER}`,
        '[Unit]',
        'Description=Vite local TLS proxy',
        'After=network.target',
        '',
        '[Service]',
        'Type=simple',
        `User=${os.userInfo().username}`,
        `Environment=HOME="${os.homedir()}"`,
        `Environment=VITE_LOCAL_TLS_RUNTIME_DIRECTORY="${options.paths.runtimeDirectory}"`,
        `ExecStart="${installed.record!.nodePath}" "${installed.record!.cliPath}" "proxy" "start" "--service" "--namespace" "default"`,
        'Restart=on-failure',
        'RestartSec=1',
        'AmbientCapabilities=CAP_NET_BIND_SERVICE',
        'CapabilityBoundingSet=CAP_NET_BIND_SERVICE',
        'NoNewPrivileges=true',
        'PrivateTmp=false',
        '',
        '[Install]',
        'WantedBy=multi-user.target',
        '',
      ].join('\n'),
    );
    await writeFile(cliPath, "console.log('older');\n");
    runner.mockClear();

    await expect(
      getStartupServiceUpdateStatus({ ...options, currentVersion: '2.9.0' }),
    ).resolves.toBe('newer');
    await installStartupService({ ...options, currentVersion: '2.9.0' });

    expect(runner).toHaveBeenCalledOnce();
    expect(runner).toHaveBeenCalledWith('systemctl', ['start', 'vite-local-tls-default.service']);
    await expect(readFile(installed.record!.cliPath, 'utf8')).resolves.toBe(
      "console.log('newer');\n",
    );
  });

  it('refuses to downgrade a newer service that requires a future control protocol', async () => {
    const cliPath = path.join(temporaryDirectory, 'cli.js');
    const options = {
      platform: 'linux' as const,
      namespace: 'default',
      paths: statePaths(),
      nodePath: process.execPath,
      cliPath,
      currentVersion: '3.0.0',
      definitionDirectory: path.join(temporaryDirectory, 'systemd'),
      runner: vi.fn(async () => ({ stdout: '', stderr: '' })),
      useSudo: false,
    };
    await writeFile(cliPath, "console.log('newer');\n");
    const installed = await installStartupService(options);
    const recordPath = path.join(options.paths.stateDirectory, 'service-install-v2.json');
    const record = JSON.parse(await readFile(recordPath, 'utf8')) as Record<string, unknown>;
    record.packageVersion = '4.0.0';
    record.protocolVersion = 2;
    await writeFile(recordPath, `${JSON.stringify(record, null, 2)}\n`);
    await writeFile(cliPath, "console.log('older');\n");
    options.runner.mockClear();

    await expect(getStartupServiceUpdateStatus(options)).resolves.toBe('newer-incompatible');
    await expect(installStartupService(options)).rejects.toThrow(/newer plugin version/);
    expect(options.runner).not.toHaveBeenCalled();
    await expect(readFile(installed.record!.cliPath, 'utf8')).resolves.toBe(
      "console.log('newer');\n",
    );
  });
});
