import { mkdir, mkdtemp, rename, rm, symlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import type { ServiceInstallationRecord } from './interfaces/service-install-options.js';
import { STARTUP_SERVICE_OWNER_MARKER } from './service-install.js';
import { discoverStartupServiceInstallations } from './service-installation-discovery.js';
import { getStatePaths } from './state-paths.js';

const ownerMarker = 'generated by @vampaz/vite-plugin-local-tls';
let temporaryDirectory: string;
let environment: NodeJS.ProcessEnv;
let definitionDirectory: string;

function record(namespace: string, version: 1 | 2 = 1): ServiceInstallationRecord {
  const paths = getStatePaths(namespace, 'linux', environment);
  const identifier = `vite-local-tls-${namespace}`;
  const runtimeDirectory = path.join(paths.stateDirectory, 'service-runtime');
  const shared = {
    platform: 'linux' as const,
    namespace,
    identifier,
    definitionPath: path.join(definitionDirectory, `${identifier}.service`),
    nodePath: path.join(runtimeDirectory, 'node'),
    cliPath: path.join(runtimeDirectory, `cli-${namespace}.js`),
    runtimeDirectory,
    controlSocket: null,
    installedAt: '2026-08-28T00:00:00.000Z',
  };
  return version === 1
    ? { version, ...shared }
    : {
        version,
        packageVersion: '1.0.0',
        protocolVersion: 1,
        installationState: 'installed',
        ...shared,
      };
}

async function writeInstallation(
  installation: ServiceInstallationRecord,
  definition?: string,
): Promise<void> {
  const paths = getStatePaths(installation.namespace, 'linux', environment);
  await Promise.all([
    mkdir(paths.stateDirectory, { recursive: true }),
    mkdir(definitionDirectory, { recursive: true }),
  ]);
  await writeFile(
    path.join(
      paths.stateDirectory,
      installation.version === 2 ? 'service-install-v2.json' : 'service-install.json',
    ),
    `${JSON.stringify(installation)}\n`,
  );
  const arguments_ = [
    installation.nodePath,
    installation.cliPath,
    'proxy',
    'start',
    '--service',
    '--namespace',
    installation.namespace,
  ];
  if (installation.controlSocket) {
    arguments_.push('--control-socket', installation.controlSocket);
  }
  await writeFile(
    installation.definitionPath!,
    definition ??
      [
        `# ${installation.version === 1 ? ownerMarker : STARTUP_SERVICE_OWNER_MARKER}`,
        '[Unit]',
        'Description=Vite local TLS proxy',
        'After=network.target',
        '',
        '[Service]',
        'Type=simple',
        'User=developer',
        `Environment=HOME="${environment.HOME}"`,
        `Environment=VITE_LOCAL_TLS_RUNTIME_DIRECTORY="${paths.runtimeDirectory}"`,
        `ExecStart=${arguments_.map((argument) => `"${argument}"`).join(' ')}`,
        'Restart=on-failure',
        'RestartSec=1',
        'AmbientCapabilities=CAP_NET_BIND_SERVICE',
        'CapabilityBoundingSet=CAP_NET_BIND_SERVICE',
        'NoNewPrivileges=true',
        'PrivateTmp=false',
        '',
        '[Install]',
        'WantedBy=multi-user.target',
        '',
      ].join('\n'),
  );
}

beforeEach(async () => {
  temporaryDirectory = await mkdtemp(path.join(os.tmpdir(), 'vite-local-tls-discovery-'));
  environment = {
    HOME: path.join(temporaryDirectory, 'home'),
    XDG_STATE_HOME: path.join(temporaryDirectory, 'state'),
    XDG_RUNTIME_DIR: path.join(temporaryDirectory, 'runtime'),
    USER: 'developer',
  };
  definitionDirectory = path.join(temporaryDirectory, 'systemd');
});

afterEach(async () => {
  await rm(temporaryDirectory, { recursive: true, force: true });
});

describe('startup service installation discovery', () => {
  it('separates the canonical service from valid owned legacy services', async () => {
    await writeInstallation(record('default', 2));
    await writeInstallation(record('playground'));

    const inventory = await discoverStartupServiceInstallations({
      platform: 'linux',
      environment,
      definitionDirectory,
      nodePath: process.execPath,
      cliPath: '/current/cli.js',
      useSudo: false,
    });

    expect(inventory.canonical?.record.namespace).toBe('default');
    expect(inventory.legacy.map(({ record: installation }) => installation.namespace)).toEqual([
      'playground',
    ]);
    expect(inventory.invalid).toEqual([]);
  });

  it('reports corrupt, incomplete, tampered, and unrelated records without owning them', async () => {
    const corruptPaths = getStatePaths('corrupt', 'linux', environment);
    await mkdir(corruptPaths.stateDirectory, { recursive: true });
    await writeFile(path.join(corruptPaths.stateDirectory, 'service-install.json'), '{broken');

    const missing = record('missing');
    const missingPaths = getStatePaths('missing', 'linux', environment);
    await mkdir(missingPaths.stateDirectory, { recursive: true });
    await writeFile(
      path.join(missingPaths.stateDirectory, 'service-install.json'),
      `${JSON.stringify(missing)}\n`,
    );

    await writeInstallation({ ...record('tampered'), runtimeDirectory: '/etc' });
    const invalidVersion = record('invalid-version', 2);
    if (invalidVersion.version !== 2) {
      throw new Error('Expected a v2 test record.');
    }
    invalidVersion.packageVersion = 'latest';
    await writeInstallation(invalidVersion);
    await writeInstallation({ ...record('invalid-date'), installedAt: 'sometime' });
    await writeInstallation(record('unrelated'), '[Service]\nExecStart=/usr/bin/other\n');
    await writeInstallation(
      record('other-user'),
      [
        `# ${ownerMarker}`,
        '[Service]',
        'User=another-developer',
        `Environment=HOME="${environment.HOME}"`,
        `Environment=VITE_LOCAL_TLS_RUNTIME_DIRECTORY="${getStatePaths('other-user', 'linux', environment).runtimeDirectory}"`,
        `ExecStart="${record('other-user').nodePath}" "${record('other-user').cliPath}" "proxy" "start" "--service" "--namespace" "other-user"`,
        '',
      ].join('\n'),
    );

    const inventory = await discoverStartupServiceInstallations({
      platform: 'linux',
      environment,
      definitionDirectory,
      nodePath: process.execPath,
      cliPath: '/current/cli.js',
      useSudo: false,
    });

    expect(inventory.legacy).toEqual([]);
    expect(inventory.invalid.map(({ namespace, reason }) => [namespace, reason]).sort()).toEqual([
      ['corrupt', 'corrupt-record'],
      ['invalid-date', 'corrupt-record'],
      ['invalid-version', 'corrupt-record'],
      ['missing', 'missing-definition'],
      ['other-user', 'unrelated-definition'],
      ['tampered', 'unsafe-target'],
      ['unrelated', 'unrelated-definition'],
    ]);
  });

  it('does not follow a symlinked installation record', async () => {
    const outsidePath = path.join(temporaryDirectory, 'outside.json');
    const paths = getStatePaths('linked', 'linux', environment);
    await mkdir(paths.stateDirectory, { recursive: true });
    await writeFile(outsidePath, `${JSON.stringify(record('linked'))}\n`);
    await import('node:fs/promises').then(({ symlink }) =>
      symlink(outsidePath, path.join(paths.stateDirectory, 'service-install.json')),
    );

    const inventory = await discoverStartupServiceInstallations({
      platform: 'linux',
      environment,
      definitionDirectory,
      nodePath: process.execPath,
      cliPath: '/current/cli.js',
      useSudo: false,
    });

    expect(inventory.legacy).toEqual([]);
    expect(inventory.invalid).toEqual([
      expect.objectContaining({ namespace: 'linked', reason: 'unsafe-record' }),
    ]);
  });

  it('does not follow a symlinked namespace directory', async () => {
    const source = record('symlink-source');
    await writeInstallation(source);
    const stateRoot = path.dirname(getStatePaths('default', 'linux', environment).stateDirectory);
    await symlink(
      getStatePaths(source.namespace, 'linux', environment).stateDirectory,
      path.join(stateRoot, 'linked-namespace'),
      'dir',
    );

    const inventory = await discoverStartupServiceInstallations({
      platform: 'linux',
      environment,
      definitionDirectory,
      nodePath: process.execPath,
      cliPath: '/current/cli.js',
      useSudo: false,
    });

    expect(inventory.legacy.map(({ record: installation }) => installation.namespace)).toEqual([
      'symlink-source',
    ]);
    expect(inventory.invalid).toEqual([
      expect.objectContaining({ namespace: 'linked-namespace', reason: 'unsafe-record' }),
    ]);
  });

  it('discovers verified canonical recovery state before and after a pending v2 record exists', async () => {
    const previous = record('default');
    const paths = getStatePaths('default', 'linux', environment);
    const legacyPath = path.join(paths.stateDirectory, 'service-install.json');
    const previousPath = path.join(paths.stateDirectory, 'service-install-previous.json');
    await writeInstallation(previous);
    await rename(legacyPath, previousPath);

    const recoveryInventory = await discoverStartupServiceInstallations({
      platform: 'linux',
      environment,
      definitionDirectory,
      nodePath: process.execPath,
      cliPath: '/current/cli.js',
      useSudo: false,
    });
    expect(recoveryInventory.canonical?.record).toMatchObject({ version: 1 });
    expect(recoveryInventory.invalid).toEqual([]);

    await writeFile(
      path.join(paths.stateDirectory, 'service-install-v2.json'),
      `${JSON.stringify({
        ...previous,
        version: 2,
        packageVersion: '2.0.0',
        protocolVersion: 1,
        installationState: 'installing',
      })}\n`,
    );
    const pendingInventory = await discoverStartupServiceInstallations({
      platform: 'linux',
      environment,
      definitionDirectory,
      nodePath: process.execPath,
      cliPath: '/current/cli.js',
      useSudo: false,
    });
    expect(pendingInventory.canonical?.record).toMatchObject({
      version: 2,
      installationState: 'installing',
    });
    expect(pendingInventory.invalid).toEqual([]);
  });

  it('keeps an interrupted first canonical installation retryable when its pending target is exact', async () => {
    const pending = record('default', 2);
    if (pending.version !== 2) {
      throw new Error('Expected a v2 test record.');
    }
    pending.installationState = 'installing';
    await writeInstallation(pending);

    const inventory = await discoverStartupServiceInstallations({
      platform: 'linux',
      environment,
      definitionDirectory,
      nodePath: process.execPath,
      cliPath: '/current/cli.js',
      useSudo: false,
    });

    expect(inventory.canonical?.record).toMatchObject({
      version: 2,
      installationState: 'installing',
    });
    expect(inventory.invalid).toEqual([]);
  });

  it('rejects an interrupted first canonical installation whose pending target is missing', async () => {
    const pending = record('default', 2);
    if (pending.version !== 2) {
      throw new Error('Expected a v2 test record.');
    }
    pending.installationState = 'installing';
    const paths = getStatePaths('default', 'linux', environment);
    await mkdir(paths.stateDirectory, { recursive: true });
    await writeFile(
      path.join(paths.stateDirectory, 'service-install-v2.json'),
      `${JSON.stringify(pending)}\n`,
    );

    const inventory = await discoverStartupServiceInstallations({
      platform: 'linux',
      environment,
      definitionDirectory,
      nodePath: process.execPath,
      cliPath: '/current/cli.js',
      useSudo: false,
    });

    expect(inventory.canonical).toBeNull();
    expect(inventory.invalid).toEqual([
      expect.objectContaining({ namespace: 'default', reason: 'missing-definition' }),
    ]);
  });
});
