import { execFile } from 'node:child_process';
import { access, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { CommandExecutionOptions } from './interfaces/command-execution-options.js';
import type { StatePaths } from './interfaces/state-paths.js';
import { installStartupService, uninstallStartupService } from './service-install.js';

let temporaryDirectory: string;
let cliFixturePath: string;

function compileAppleScript(arguments_: string[], outputPath: string): Promise<void> {
  return new Promise((resolve, reject) => {
    execFile('/usr/bin/osacompile', ['-o', outputPath, ...arguments_], (error) => {
      if (error) {
        reject(error);
        return;
      }
      resolve();
    });
  });
}

function statePaths(): StatePaths {
  const stateDirectory = path.join(temporaryDirectory, 'state');
  const runtimeDirectory = path.join(temporaryDirectory, 'runtime', 'test');
  return {
    stateDirectory,
    runtimeDirectory,
    socketPath: path.join(runtimeDirectory, 'control.sock'),
    lockPath: path.join(runtimeDirectory, 'startup.lock'),
    stateFile: path.join(stateDirectory, 'service.json'),
    certificateDirectory: path.join(stateDirectory, 'certificates'),
    importedCertificateDirectory: path.join(stateDirectory, 'imported'),
    caKeyPath: path.join(stateDirectory, 'ca-key.pem'),
    caCertificatePath: path.join(stateDirectory, 'ca.pem'),
    caStatePath: path.join(stateDirectory, 'ca.json'),
  };
}

beforeEach(async () => {
  vi.stubEnv('CI', '');
  temporaryDirectory = await mkdtemp(path.join(os.tmpdir(), 'vite-local-tls-launchd-'));
  cliFixturePath = path.join(temporaryDirectory, 'project', 'dist', 'cli.js');
  await mkdir(path.dirname(cliFixturePath), { recursive: true });
  await writeFile(cliFixturePath, 'export {};\n');
});

afterEach(async () => {
  vi.unstubAllEnvs();
  await rm(temporaryDirectory, { recursive: true, force: true });
});

describe('macOS startup service', () => {
  it('installs and removes a root launch daemon through elevation', async () => {
    let definition = '';
    const paths = statePaths();
    const temporaryDefinitionPath = path.join(
      paths.stateDirectory,
      'com.vampaz.vite-local-tls.test.plist.tmp',
    );
    const runner = vi.fn(
      async (_command: string, _arguments: string[], _options?: CommandExecutionOptions) => {
        definition = await readFile(temporaryDefinitionPath, 'utf8').catch(() => definition);
        return { stdout: '', stderr: '' };
      },
    );
    const options = {
      platform: 'darwin' as const,
      namespace: 'test',
      paths,
      nodePath: '/opt/homebrew/bin/node',
      cliPath: cliFixturePath,
      homeDirectory: temporaryDirectory,
      uid: 501,
      username: 'developer',
      definitionDirectory: path.join(temporaryDirectory, 'Library', 'LaunchDaemons'),
      runtimeInstallDirectory: path.join(temporaryDirectory, 'system-runtime'),
      runner,
    };

    const installed = await installStartupService(options);
    const definitionPath = installed.record?.definitionPath ?? '';
    expect(definition).toContain('generated by @vampaz/vite-plugin-local-tls');
    expect(definition).toContain('<string>--run-as-uid</string>');
    expect(definition).toContain('<string>501</string>');
    expect(definition).toContain('<string>--service</string>');
    expect(definition).toContain('<string>--namespace</string>');
    expect(definition).not.toContain('<key>UserName</key>');
    expect(definition).toContain('<key>VITE_LOCAL_TLS_USER_ID</key>');
    expect(definition).toContain('<key>VITE_LOCAL_TLS_RUNTIME_DIRECTORY</key>');
    expect(definition).toContain(options.paths.runtimeDirectory);
    expect(definition).toContain('<string>developer</string>');
    expect(installed.record?.nodePath).toBe(
      path.join(temporaryDirectory, 'system-runtime', 'node'),
    );
    expect(installed.record?.cliPath).toBe(
      path.join(temporaryDirectory, 'system-runtime', 'cli.js'),
    );
    expect(runner).toHaveBeenCalledOnce();
    const installCall = runner.mock.calls[0]!;
    const installSequence = JSON.parse(installCall[1].at(-1)!) as Array<{
      command: string;
      arguments_: string[];
      allowFailure?: boolean;
    }>;
    expect(installCall[0]).toBe('/usr/bin/osascript');
    expect(
      installCall[1].some((argument) =>
        argument.includes(
          'do shell script (commandPath & " --input-type=module --eval " & source & " " & requests) with administrator privileges',
        ),
      ),
    ).toBe(true);
    expect(installCall[1].slice(-3)).toEqual([
      process.execPath,
      expect.any(String),
      expect.any(String),
    ]);
    expect(installCall[1].slice(0, 4)).toEqual(['-e', 'on run argv', '-e', expect.any(String)]);
    expect(installCall[1]).not.toContain('--');
    expect(installCall[2]).toBeUndefined();
    expect(installCall[1].at(-2)).toContain('spawnSync(request.command, request.arguments_');
    expect(installCall[1].at(-2)).toContain('timeout: 15_000');
    expect(installSequence.map(({ command }) => command)).toEqual([
      'mkdir',
      'install',
      'install',
      'install',
      'launchctl',
      process.execPath,
      'launchctl',
      'launchctl',
      'launchctl',
    ]);
    expect(installSequence[4]).toMatchObject({ allowFailure: true });
    expect(installSequence[5]?.arguments_).toEqual([
      '--input-type=module',
      '--eval',
      expect.any(String),
      'com.vampaz.vite-local-tls.test',
    ]);
    expect(installSequence[6]?.arguments_).toEqual(['bootstrap', 'system', definitionPath]);
    if (process.platform === 'darwin') {
      await compileAppleScript(
        installCall[1].slice(0, -3),
        path.join(temporaryDirectory, 'authorization.scpt'),
      );
    }

    await uninstallStartupService(options);

    await expect(access(definitionPath)).rejects.toThrow();
    expect(runner).toHaveBeenCalledTimes(2);
    const uninstallCall = runner.mock.calls[1]!;
    const uninstallSequence = JSON.parse(uninstallCall[1].at(-1)!) as Array<{
      command: string;
      arguments_: string[];
      allowFailure?: boolean;
    }>;
    expect(uninstallCall[0]).toBe('/usr/bin/osascript');
    expect(uninstallCall[2]).toBeUndefined();
    expect(uninstallSequence.map(({ command }) => command)).toEqual([
      'launchctl',
      process.execPath,
      'rm',
      'rm',
    ]);
    expect(uninstallSequence[0]).toMatchObject({ allowFailure: true });
    expect(uninstallSequence[1]?.arguments_).toEqual([
      '--input-type=module',
      '--eval',
      expect.any(String),
      'com.vampaz.vite-local-tls.test',
    ]);
  });

  it('does not expose a protected project CLI path to the elevated installer', async () => {
    const paths = statePaths();
    const protectedCliPath = path.join(
      temporaryDirectory,
      'Desktop',
      'Work.nosync',
      'project',
      'dist',
      'cli.js',
    );
    await mkdir(path.dirname(protectedCliPath), { recursive: true });
    await writeFile(protectedCliPath, 'export {};\n');
    let stagedCliPath = '';
    const runner = vi.fn(async (_command: string, arguments_: string[]) => {
      const installSequence = JSON.parse(arguments_.at(-1)!) as Array<{
        command: string;
        arguments_: string[];
      }>;
      const cliInstall = installSequence.find(
        ({ command, arguments_: commandArguments }) =>
          command === 'install' && commandArguments.at(-1)?.endsWith('/cli.js'),
      );
      stagedCliPath = cliInstall?.arguments_[2] ?? '';
      if (stagedCliPath === protectedCliPath) {
        throw new Error('Operation not permitted');
      }
      await expect(readFile(stagedCliPath, 'utf8')).resolves.toBe('export {};\n');
      return { stdout: '', stderr: '' };
    });

    await expect(
      installStartupService({
        platform: 'darwin',
        namespace: 'test',
        paths,
        nodePath: '/opt/homebrew/bin/node',
        cliPath: protectedCliPath,
        homeDirectory: temporaryDirectory,
        uid: 501,
        username: 'developer',
        definitionDirectory: path.join(temporaryDirectory, 'Library', 'LaunchDaemons'),
        runtimeInstallDirectory: path.join(temporaryDirectory, 'system-runtime'),
        runner,
      }),
    ).resolves.toMatchObject({ installed: true });
    expect(stagedCliPath).not.toBe(protectedCliPath);
    await expect(access(stagedCliPath)).rejects.toThrow();
  });

  it('refuses to overwrite an unrelated definition at the same path', async () => {
    const runner = vi.fn(async (_command: string, _arguments: string[]) => ({
      stdout: '',
      stderr: '',
    }));
    const options = {
      platform: 'darwin' as const,
      namespace: 'test',
      paths: statePaths(),
      nodePath: '/usr/bin/node',
      cliPath: cliFixturePath,
      homeDirectory: temporaryDirectory,
      definitionDirectory: path.join(temporaryDirectory, 'Library', 'LaunchDaemons'),
      runtimeInstallDirectory: path.join(temporaryDirectory, 'system-runtime'),
      runner,
    };
    await installStartupService(options);
    const definitionPath = path.join(
      temporaryDirectory,
      'Library',
      'LaunchDaemons',
      'com.vampaz.vite-local-tls.test.plist',
    );
    await mkdir(path.dirname(definitionPath), { recursive: true });
    await writeFile(definitionPath, '<plist>unrelated</plist>');

    await expect(installStartupService(options)).rejects.toThrow(/unrelated service definition/);
  });

  it('does not leave an installation record when authorization is cancelled', async () => {
    const runner = vi.fn(
      async (_command: string, _arguments: string[], _options?: CommandExecutionOptions) => {
        throw new Error('Authorization cancelled.');
      },
    );
    const options = {
      platform: 'darwin' as const,
      namespace: 'test',
      paths: statePaths(),
      nodePath: '/usr/bin/node',
      cliPath: cliFixturePath,
      homeDirectory: temporaryDirectory,
      definitionDirectory: path.join(temporaryDirectory, 'Library', 'LaunchDaemons'),
      runtimeInstallDirectory: path.join(temporaryDirectory, 'system-runtime'),
      runner,
    };

    await expect(installStartupService(options)).rejects.toThrow(/Authorization cancelled/);
    await expect(
      access(path.join(options.paths.stateDirectory, 'service-install.json')),
    ).rejects.toThrow();
    await expect(access(options.runtimeInstallDirectory)).rejects.toThrow();
    await expect(
      access(path.join(options.definitionDirectory, 'com.vampaz.vite-local-tls.test.plist')),
    ).rejects.toThrow();
    expect(runner).toHaveBeenCalledWith('/usr/bin/osascript', expect.any(Array));
  });

  it('refuses a tampered recursive runtime deletion target', async () => {
    const runner = vi.fn(async (_command: string, _arguments: string[]) => ({
      stdout: '',
      stderr: '',
    }));
    const options = {
      platform: 'darwin' as const,
      namespace: 'test',
      paths: statePaths(),
      nodePath: '/usr/bin/node',
      cliPath: cliFixturePath,
      homeDirectory: temporaryDirectory,
      definitionDirectory: path.join(temporaryDirectory, 'Library', 'LaunchDaemons'),
      runtimeInstallDirectory: path.join(temporaryDirectory, 'system-runtime'),
      runner,
    };
    await installStartupService(options);
    const installationRecordPath = path.join(options.paths.stateDirectory, 'service-install.json');
    const record = JSON.parse(await readFile(installationRecordPath, 'utf8')) as Record<
      string,
      unknown
    >;
    await writeFile(
      installationRecordPath,
      `${JSON.stringify({ ...record, runtimeDirectory: '/Library' })}\n`,
    );

    await expect(uninstallStartupService(options)).rejects.toThrow(/unexpected runtime target/);
    expect(runner.mock.calls.some(([, arguments_]) => arguments_.includes('/Library'))).toBe(false);
  });
});
