import { access, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { StatePaths } from './interfaces/state-paths.js';
import { installStartupService, uninstallStartupService } from './service-install.js';

let temporaryDirectory: string;

function statePaths(): StatePaths {
  const stateDirectory = path.join(temporaryDirectory, 'state');
  const runtimeDirectory = path.join(temporaryDirectory, 'runtime', 'test');
  return {
    stateDirectory,
    runtimeDirectory,
    socketPath: path.join(runtimeDirectory, 'control.sock'),
    lockPath: path.join(runtimeDirectory, 'startup.lock'),
    stateFile: path.join(stateDirectory, 'service.json'),
    certificateDirectory: path.join(stateDirectory, 'certificates'),
    importedCertificateDirectory: path.join(stateDirectory, 'imported'),
    caKeyPath: path.join(stateDirectory, 'ca-key.pem'),
    caCertificatePath: path.join(stateDirectory, 'ca.pem'),
    caStatePath: path.join(stateDirectory, 'ca.json'),
  };
}

beforeEach(async () => {
  temporaryDirectory = await mkdtemp(path.join(os.tmpdir(), 'vite-local-tls-launchd-'));
});

afterEach(async () => {
  await rm(temporaryDirectory, { recursive: true, force: true });
});

describe('macOS startup service', () => {
  it('installs and removes a root launch daemon through elevation', async () => {
    let definition = '';
    const runner = vi.fn(async (_command: string, arguments_: string[]) => {
      const temporaryPath = arguments_.find((argument) => argument.endsWith('.plist.tmp'));
      if (temporaryPath) {
        definition = await readFile(temporaryPath, 'utf8');
      }
      return { stdout: '', stderr: '' };
    });
    const options = {
      platform: 'darwin' as const,
      namespace: 'test',
      paths: statePaths(),
      nodePath: '/opt/homebrew/bin/node',
      cliPath: '/project/dist/cli.js',
      homeDirectory: temporaryDirectory,
      uid: 501,
      username: 'developer',
      definitionDirectory: path.join(temporaryDirectory, 'Library', 'LaunchDaemons'),
      runtimeInstallDirectory: path.join(temporaryDirectory, 'system-runtime'),
      runner,
    };

    const installed = await installStartupService(options);
    const definitionPath = installed.record?.definitionPath ?? '';
    expect(definition).toContain('generated by @vampaz/vite-plugin-local-tls');
    expect(definition).toContain('<string>--run-as-uid</string>');
    expect(definition).toContain('<string>501</string>');
    expect(definition).toContain('<string>--service</string>');
    expect(definition).toContain('<string>--namespace</string>');
    expect(definition).not.toContain('<key>UserName</key>');
    expect(definition).toContain('<key>VITE_LOCAL_TLS_USER_ID</key>');
    expect(definition).toContain('<key>VITE_LOCAL_TLS_RUNTIME_DIRECTORY</key>');
    expect(definition).toContain(options.paths.runtimeDirectory);
    expect(definition).toContain('<string>developer</string>');
    expect(installed.record?.nodePath).toBe(
      path.join(temporaryDirectory, 'system-runtime', 'node'),
    );
    expect(installed.record?.cliPath).toBe(
      path.join(temporaryDirectory, 'system-runtime', 'cli.js'),
    );
    expect(runner).toHaveBeenCalledWith('sudo', [
      '--',
      'install',
      '-m',
      '0755',
      '/opt/homebrew/bin/node',
      path.join(temporaryDirectory, 'system-runtime', 'node'),
    ]);
    expect(runner).toHaveBeenCalledWith('sudo', [
      '--',
      'launchctl',
      'bootstrap',
      'system',
      definitionPath,
    ]);

    await uninstallStartupService(options);

    await expect(access(definitionPath)).rejects.toThrow();
    expect(runner).toHaveBeenCalledWith('sudo', [
      '--',
      'launchctl',
      'bootout',
      'system/com.vampaz.vite-local-tls.test',
    ]);
  });

  it('refuses to overwrite an unrelated definition at the same path', async () => {
    const runner = vi.fn(async (_command: string, _arguments: string[]) => ({
      stdout: '',
      stderr: '',
    }));
    const options = {
      platform: 'darwin' as const,
      namespace: 'test',
      paths: statePaths(),
      nodePath: '/usr/bin/node',
      cliPath: '/project/dist/cli.js',
      homeDirectory: temporaryDirectory,
      definitionDirectory: path.join(temporaryDirectory, 'Library', 'LaunchDaemons'),
      runtimeInstallDirectory: path.join(temporaryDirectory, 'system-runtime'),
      runner,
    };
    await installStartupService(options);
    const definitionPath = path.join(
      temporaryDirectory,
      'Library',
      'LaunchDaemons',
      'com.vampaz.vite-local-tls.test.plist',
    );
    await mkdir(path.dirname(definitionPath), { recursive: true });
    await writeFile(definitionPath, '<plist>unrelated</plist>');

    await expect(installStartupService(options)).rejects.toThrow(/unrelated service definition/);
  });

  it('refuses a tampered recursive runtime deletion target', async () => {
    const runner = vi.fn(async (_command: string, _arguments: string[]) => ({
      stdout: '',
      stderr: '',
    }));
    const options = {
      platform: 'darwin' as const,
      namespace: 'test',
      paths: statePaths(),
      nodePath: '/usr/bin/node',
      cliPath: '/project/dist/cli.js',
      homeDirectory: temporaryDirectory,
      definitionDirectory: path.join(temporaryDirectory, 'Library', 'LaunchDaemons'),
      runtimeInstallDirectory: path.join(temporaryDirectory, 'system-runtime'),
      runner,
    };
    await installStartupService(options);
    const installationRecordPath = path.join(options.paths.stateDirectory, 'service-install.json');
    const record = JSON.parse(await readFile(installationRecordPath, 'utf8')) as Record<
      string,
      unknown
    >;
    await writeFile(
      installationRecordPath,
      `${JSON.stringify({ ...record, runtimeDirectory: '/Library' })}\n`,
    );

    await expect(uninstallStartupService(options)).rejects.toThrow(/unexpected runtime target/);
    expect(runner.mock.calls.some(([, arguments_]) => arguments_.includes('/Library'))).toBe(false);
  });
});
